/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Govt_Coordinator;
import Plasma_DB4OUtil.DB4OUtil;
import Plasma.EcoSystem;
import Plasma_People.Donor;
import Plasma_People.Donor_Req;
import HomePages.TableFormat;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RST
 */
public class Donor_Status_JPanel extends javax.swing.JPanel {

    // Creates new form Donor_Status
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public Donor_Status_JPanel(EcoSystem system) {
        initComponents();
        this.system = system;
        donorRequestTable.getTableHeader().setDefaultRenderer(new TableFormat());
        donorRequestTable1.getTableHeader().setDefaultRenderer(new TableFormat());
        viewTable();
        populateTableS();
    }

    private void viewTable() {
        DefaultTableModel t = (DefaultTableModel) donorRequestTable.getModel();
        t.setRowCount(0);
        
        for (Donor donor : system.getDonorDir().getDonor_List()) {
            Object row[] = new Object[4];
            row[0] = donor;
            row[1] = donor.getName();
            row[2] = donor.getMobile();
            row[3] = donor.getRecent_status();

            t.addRow(row);
        }
    }
    private void populateTableS() {
        DefaultTableModel t = (DefaultTableModel) donorRequestTable1.getModel();
        t.setRowCount(0);

        for (Donor_Req donor : system.getDonorRequestDir().getDonor_Req_List()) {
            Object row[] = new Object[4];
            row[0] = donor;
            row[1] = donor.getName();
            row[2] = donor.getContact();
            row[3] = donor.getStatus();

            t.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        donorRequestTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        donorRequestTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donorRequestTable.setBackground(new java.awt.Color(102, 0, 102));
        donorRequestTable.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        donorRequestTable.setForeground(new java.awt.Color(255, 255, 255));
        donorRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DONOR ID", "NAME", "CONTACT", "STATUS"
            }
        ));
        donorRequestTable.setGridColor(new java.awt.Color(0, 0, 0));
        donorRequestTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        donorRequestTable.setRowHeight(30);
        donorRequestTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(donorRequestTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 660, 330));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("DONORS MANAGEMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 1696, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 1720, -1));

        jButton1.setBackground(new java.awt.Color(31, 31, 31));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jButton1.setText("DELETE/REMOVE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_button(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 230, 39));

        donorRequestTable1.setBackground(new java.awt.Color(102, 0, 102));
        donorRequestTable1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        donorRequestTable1.setForeground(new java.awt.Color(255, 255, 255));
        donorRequestTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DONOR ID", "NAME", "CONTACT", "STATUS"
            }
        ));
        donorRequestTable1.setGridColor(new java.awt.Color(0, 0, 0));
        donorRequestTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        donorRequestTable1.setRowHeight(30);
        donorRequestTable1.setShowVerticalLines(false);
        jScrollPane2.setViewportView(donorRequestTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 590, 340));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 122, 30, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void delete_button(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button
        // TODO add your handling code here:       
        int row = donorRequestTable1.getSelectedRow();
        Donor_Req dr = ((Donor_Req) donorRequestTable1.getValueAt(row, 0));

        system.getDonorRequestDir().removeDonorRequest(dr);

        dB4OUtil.storeSystem(system);
        populateTableS();
    }//GEN-LAST:event_delete_button


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable donorRequestTable;
    private javax.swing.JTable donorRequestTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
