/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Govt_Coordinator;
import HomePages.TableFormat;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RST
 */
public class Encourage_Cured_Patients_JPanel extends javax.swing.JPanel {

    //Creates new form Check Old Patients
    public Encourage_Cured_Patients_JPanel() {
        initComponents();
        tblCuredPatient.getTableHeader().setDefaultRenderer(new TableFormat());
        viewTable();
    }

    //view all the details in a table
    
    private void viewTable() {
        DefaultTableModel dtmA = (DefaultTableModel) tblCuredPatient.getModel();
        dtmA.setRowCount(0);
        Object row[] = new Object[4];
        String line = "";
        String splitBy = ",";
        try {
            //parsing a CSV file into BufferedReader class constructor  
            BufferedReader br = new BufferedReader(new FileReader("CuredPatientsRecord.csv"));
            while ((line = br.readLine()) != null) 
            {
                String[] csv = line.split(splitBy);  
                row[0] = csv[0];
                row[1] = csv[1];
                row[2] = csv[2];
                row[3] = csv[3];

                dtmA.addRow(row);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuredPatient = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCuredPatient.setBackground(new java.awt.Color(102, 0, 102));
        tblCuredPatient.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblCuredPatient.setForeground(new java.awt.Color(255, 255, 255));
        tblCuredPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UID", "NAME", "EMAIL", "COVID CURE DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCuredPatient.setGridColor(new java.awt.Color(0, 0, 0));
        tblCuredPatient.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblCuredPatient.setRowHeight(30);
        tblCuredPatient.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblCuredPatient);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 980, 220));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" CURED PATIENTS LIST WITH CONTACT DETAILS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 580, -1));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("COMMUNICATE CURED COVID PATIENTS FOR DONATION");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 1606, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1630, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCuredPatient;
    // End of variables declaration//GEN-END:variables
}
