
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Govt_Coordinator;
import Plasma_DB4OUtil.DB4OUtil;
import Plasma.EcoSystem;
import Plasma_People.Donor;
import Plasma_People.Donor_Req;
import HomePages.TableFormat;
import java.awt.Color;
import java.awt.Image;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RST  
 */
public class Volunteer_Donor_Request_JPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    Volunteer_Donor_Request_JPanel(EcoSystem system) {
        initComponents();
        this.system = system;
        requestTable.getTableHeader().setDefaultRenderer(new TableFormat());
        viewRequestTable();
    }

    private void viewRequestTable() {
        DefaultTableModel t = (DefaultTableModel) requestTable.getModel();

        t.setRowCount(0);

        for (Donor_Req dnr : system.getDonorRequestDir().getDonor_Req_List()) {
            System.out.println("Printing here in Volunteer !!");
            System.out.println(dnr.getName());
        }

        for (Donor_Req donorRequest : system.getDonorRequestDir().getDonor_Req_List()) {
            Object row[] = new Object[4];
            row[0] = donorRequest;
            row[1] = donorRequest.getName();
            row[2] = donorRequest.getContact();
            row[3] = donorRequest.getStatus();
            t.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        button_Approve = new javax.swing.JButton();
        button_Reject = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        uidText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        genderText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        streetText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bloodText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        stateText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        zipText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        contactText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        statusText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        lastDaySymptomsText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        button_Details = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        labConfirmationText = new javax.swing.JTextField();
        followUpTest = new javax.swing.JTextField();
        symptomsText = new javax.swing.JTextField();
        lblProfilePicture = new javax.swing.JLabel();
        dobDateField = new com.toedter.calendar.JDateChooser();
        diagnosedDateField = new com.toedter.calendar.JDateChooser();
        curedDateField = new com.toedter.calendar.JDateChooser();
        lastDonationDateField = new com.toedter.calendar.JDateChooser();
        emailText = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTable.setBackground(new java.awt.Color(102, 0, 102));
        requestTable.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        requestTable.setForeground(new java.awt.Color(255, 255, 255));
        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UID", "NAME", "CONTACT", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        requestTable.setFocusable(false);
        requestTable.setGridColor(new java.awt.Color(0, 0, 0));
        requestTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        requestTable.setRowHeight(30);
        requestTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(requestTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 550, 320));

        button_Approve.setBackground(new java.awt.Color(31, 31, 31));
        button_Approve.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        button_Approve.setText("APPROVE");
        button_Approve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button_Approve.setEnabled(false);
        button_Approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_button(evt);
            }
        });
        add(button_Approve, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 720, 100, 40));

        button_Reject.setBackground(new java.awt.Color(31, 31, 31));
        button_Reject.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        button_Reject.setForeground(new java.awt.Color(255, 255, 255));
        button_Reject.setText("REJECT");
        button_Reject.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button_Reject.setEnabled(false);
        button_Reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reject_button(evt);
            }
        });
        add(button_Reject, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 720, 100, 40));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("UID:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 30));

        uidText.setBackground(new java.awt.Color(0, 0, 0));
        uidText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        uidText.setForeground(new java.awt.Color(255, 255, 255));
        add(uidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 170, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("DOB:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 30));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setText("AGE:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        ageText.setBackground(new java.awt.Color(0, 0, 0));
        ageText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        ageText.setForeground(new java.awt.Color(255, 255, 255));
        add(ageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 180, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setText("GENDER:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        genderText.setBackground(new java.awt.Color(0, 0, 0));
        genderText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        genderText.setForeground(new java.awt.Color(255, 255, 255));
        add(genderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 170, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel10.setText("STATUS:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, 30));

        streetText.setBackground(new java.awt.Color(0, 0, 0));
        streetText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        streetText.setForeground(new java.awt.Color(255, 255, 255));
        add(streetText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 170, 176, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel11.setText("COVID DETECTED DATE:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, -1, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel12.setText("COVID CURRED DATE:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, -1, -1));

        bloodText.setBackground(new java.awt.Color(0, 0, 0));
        bloodText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        bloodText.setForeground(new java.awt.Color(255, 255, 255));
        add(bloodText, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 180, -1));

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel13.setText("STREET ADDRESS:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel14.setText("CITY:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, -1, 30));

        cityText.setBackground(new java.awt.Color(0, 0, 0));
        cityText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        cityText.setForeground(new java.awt.Color(255, 255, 255));
        add(cityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 210, 180, -1));

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel15.setText("STATE:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 260, -1, -1));

        stateText.setBackground(new java.awt.Color(0, 0, 0));
        stateText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        stateText.setForeground(new java.awt.Color(255, 255, 255));
        add(stateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 250, 180, -1));

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel16.setText("ZIPCODE:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 300, -1, -1));

        zipText.setBackground(new java.awt.Color(0, 0, 0));
        zipText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        zipText.setForeground(new java.awt.Color(255, 255, 255));
        add(zipText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 290, 180, -1));

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel17.setText("CONTACT NUMBER:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        contactText.setBackground(new java.awt.Color(0, 0, 0));
        contactText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        contactText.setForeground(new java.awt.Color(255, 255, 255));
        add(contactText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 170, -1));

        jLabel18.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel18.setText("EMAIL ID:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        statusText.setBackground(new java.awt.Color(0, 0, 0));
        statusText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        statusText.setForeground(new java.awt.Color(255, 255, 255));
        add(statusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 180, -1));

        jLabel19.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel19.setText("DATE OF LAST PLASMA DONATION:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, -1, -1));

        lastDaySymptomsText.setBackground(new java.awt.Color(0, 0, 0));
        lastDaySymptomsText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lastDaySymptomsText.setForeground(new java.awt.Color(255, 255, 255));
        lastDaySymptomsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastDaySymptomsTextActionPerformed(evt);
            }
        });
        add(lastDaySymptomsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 530, 170, -1));

        jLabel20.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel20.setText("WAS COVID-19 DAIGONISIS CONFIRMED BY LAB?");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, -1, -1));

        jLabel21.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel21.setText("CURRENTLY YOU DO NOT HAVE SYMPTOMS?");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, -1, -1));

        jLabel22.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel22.setText("Has it been at least 14 days since the last day of your symptoms?");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("NAME:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        jLabel24.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel24.setText("WAS YOUR FOLLOWUP TEST REPORT NEGATIVE?");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, -1, -1));

        nameText.setBackground(new java.awt.Color(0, 0, 0));
        nameText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 180, -1));

        button_Details.setBackground(new java.awt.Color(31, 31, 31));
        button_Details.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        button_Details.setText("See Details");
        button_Details.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_details(evt);
            }
        });
        add(button_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 130, 40));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("HANDLING DONOR REQUESTS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 1706, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1730, -1));

        labConfirmationText.setBackground(new java.awt.Color(0, 0, 0));
        labConfirmationText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labConfirmationText.setForeground(new java.awt.Color(255, 255, 255));
        add(labConfirmationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 390, 170, -1));

        followUpTest.setBackground(new java.awt.Color(0, 0, 0));
        followUpTest.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        followUpTest.setForeground(new java.awt.Color(255, 255, 255));
        followUpTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followUpTestActionPerformed(evt);
            }
        });
        add(followUpTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 430, 170, -1));

        symptomsText.setBackground(new java.awt.Color(0, 0, 0));
        symptomsText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        symptomsText.setForeground(new java.awt.Color(255, 255, 255));
        symptomsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symptomsTextActionPerformed(evt);
            }
        });
        add(symptomsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 480, 170, -1));

        lblProfilePicture.setBackground(new java.awt.Color(0, 0, 0));
        add(lblProfilePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 90, 130, 130));

        dobDateField.setBackground(new java.awt.Color(0, 0, 0));
        dobDateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dobDateField.setForeground(new java.awt.Color(255, 255, 255));
        dobDateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dobDateFieldFocusLost(evt);
            }
        });
        dobDateField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dobDateFieldMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dobDateFieldMousePressed(evt);
            }
        });
        dobDateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dobDateFielduDobKeyTyped(evt);
            }
        });
        add(dobDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 170, -1));

        diagnosedDateField.setBackground(new java.awt.Color(0, 0, 0));
        diagnosedDateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        diagnosedDateField.setForeground(new java.awt.Color(255, 255, 255));
        add(diagnosedDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 590, 180, -1));

        curedDateField.setBackground(new java.awt.Color(0, 0, 0));
        curedDateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        curedDateField.setForeground(new java.awt.Color(255, 255, 255));
        curedDateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                curedDateFieldUCovidCuredDateKeyTyped(evt);
            }
        });
        add(curedDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 630, 180, -1));

        lastDonationDateField.setBackground(new java.awt.Color(0, 0, 0));
        lastDonationDateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lastDonationDateField.setForeground(new java.awt.Color(255, 255, 255));
        add(lastDonationDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 670, 180, -1));

        emailText.setBackground(new java.awt.Color(0, 0, 0));
        emailText.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        emailText.setForeground(new java.awt.Color(255, 255, 255));
        add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 180, -1));

        jLabel23.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel23.setText("BLOOD GROUP:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1600, 20));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel1.setText("DONORS LIST");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setText("BIOGRAPHIC DETAILS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel4.setText("ADDRESS DETAILS");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel5.setText("COVID DETAILS");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 20, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void remove_button(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_button
        // TODO add your handling code here:
        if (!statusText.getText().equals("New Request")) {
            JOptionPane.showMessageDialog(null,"Can Not Approve the Request!");
            }
        else {
            Donor d = system.getDonorDir().addDonor();
            d.setID(uidText.getText()); 
            d.setName(nameText.getText()); 
            d.setDateOfBirth(dobDateField.getDate()); 
            d.setCOVID_Infected_Date(diagnosedDateField.getDate()); 
            d.setCOVID_Cured_Date(curedDateField.getDate());
            d.setPrevious_Donation_Date(lastDonationDateField.getDate()); 
            d.setAge(Integer.parseInt(ageText.getText()));
            d.setGender(genderText.getText()); 
            d.setBlood_Group(bloodText.getText()); 
            d.setStreet_Address(streetText.getText());
            d.setCity(cityText.getText()); 
            d.setState(stateText.getText()); 
            d.setPincode(Integer.parseInt(zipText.getText())); 
            d.setMobile((contactText.getText())); 
            d.setEmail(statusText.getText()); 
            d.setRecent_status("Government Approved"); 
            d.setLab_Confirmation(true);   
            d.setSymptoms(true);   
            d.setLast_Day_Symptoms(true);  
            d.setFollow_Up_Test(true);        

            for (Donor_Req donorRequest : system.getDonorRequestDir().getDonor_Req_List()) {

                if (donorRequest.getDonor_ID().equals(uidText.getText())) {
                    donorRequest.setStatus("Government Approved");
                    dB4OUtil.storeSystem(system);
                }
            }
            statusText.setText("Government Approved");
            dB4OUtil.storeSystem(system);
            viewRequestTable();
            JOptionPane.showMessageDialog(null, new JLabel("Request approved successfully!!!!!"));
        }
    }//GEN-LAST:event_remove_button

    private void view_details(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_details
        // TODO add your handling code here:
        int selectedRow = requestTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, new JLabel("Please select row from the table to view details!!!!!!"), "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            //display the details 
            view_Request_Details((Donor_Req) requestTable.getValueAt(selectedRow, 0));
            button_Approve.setEnabled(true);
            button_Reject.setEnabled(true);

            if (Integer.parseInt(ageText.getText()) < 18) // check if age is less than 18 years
            {
                ageText.setBorder(BorderFactory.createLineBorder(Color.RED));
                ageText.setForeground(Color.red);
            }
            if (labConfirmationText.getText().equals("false")) // Was your COVID diagnosis confirmed by a lab test?
            {
                labConfirmationText.setBorder(BorderFactory.createLineBorder(Color.RED));
                labConfirmationText.setForeground(Color.red);
            }
            if (followUpTest.getText().equals("false")) // did you have a follow up test that was negative for COVID?
            {
                followUpTest.setBorder(BorderFactory.createLineBorder(Color.RED));
                followUpTest.setForeground(Color.red);
            }
            if (symptomsText.getText().equals("false")) // Currently you do not have any symptoms? 
            {
                symptomsText.setBorder(BorderFactory.createLineBorder(Color.RED));
                symptomsText.setForeground(Color.red);
            }
            if (lastDaySymptomsText.getText().equals("false")) // Has it been at least 14 days since the last day of your symptoms?
            {
                lastDaySymptomsText.setBorder(BorderFactory.createLineBorder(Color.RED));
                lastDaySymptomsText.setForeground(Color.red);
            }
            if (new Date().getDay() - lastDonationDateField.getDate().getDay() < 30) // check if age is less than 30 years
                            {
                lastDonationDateField.setBorder(BorderFactory.createLineBorder(Color.RED));
                lastDonationDateField.setForeground(Color.red);
            }
            dB4OUtil.storeSystem(system);

        }
    }

    private void view_Request_Details(Donor_Req donorRequest) {
        uidText.setText(donorRequest.getDonor_ID());
        nameText.setText(donorRequest.getName());
        dobDateField.setDate(donorRequest.getDateOfBirth());
        curedDateField.setDate(donorRequest.getCOVID_Cured_Date());
        diagnosedDateField.setDate(donorRequest.getCOVID_Infected_Date());
        lastDonationDateField.setDate(donorRequest.getPrevious_Donation_Date());
        ageText.setText(String.valueOf(donorRequest.getAge()));
        genderText.setText(donorRequest.getGender());
        bloodText.setText(donorRequest.getBlood_Group());
        streetText.setText(donorRequest.getAddress());
        cityText.setText(donorRequest.getCity());
        stateText.setText(donorRequest.getState());
        zipText.setText(String.valueOf(donorRequest.getZipCode()));
        contactText.setText(donorRequest.getContact());
        emailText.setText(donorRequest.getEmailID());
        statusText.setText(donorRequest.getStatus());
        labConfirmationText.setText(String.valueOf(donorRequest.isLab_Confirmation()));
        followUpTest.setText(String.valueOf(donorRequest.isFollowUpTest()));
        symptomsText.setText(String.valueOf(donorRequest.isSymptoms()));
        lastDaySymptomsText.setText(String.valueOf(donorRequest.isLast_Day_Symptoms()));

        if (donorRequest.getdP() != null) {
            byte[] JLabelpictureLabel = donorRequest.getdP();
            ImageIcon i = setPicturebyte(JLabelpictureLabel);
            lblProfilePicture.setIcon(i);
        } else {
            System.err.println("No Image");
        }

        uidText.setEditable(false);
        nameText.setEditable(false);
        ageText.setEditable(false);
        genderText.setEditable(false);
        bloodText.setEditable(false);
        streetText.setEditable(false);
        cityText.setEditable(false);
        stateText.setEditable(false);
        zipText.setEditable(false);
        contactText.setEditable(false);
        statusText.setEditable(false);
        statusText.setEditable(false);
        labConfirmationText.setEditable(false);
        followUpTest.setEditable(false);
        symptomsText.setEditable(false);
        lastDaySymptomsText.setEditable(false);
        diagnosedDateField.setEnabled(false);
        dobDateField.setEnabled(false);
        curedDateField.setEnabled(false);
        lastDonationDateField.setEnabled(false);
    }//GEN-LAST:event_view_details

    private ImageIcon setPicturebyte(byte[] byteArrayImage) {
        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;
    }
    private void reject_button(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reject_button
        // TODO add your handling code here:
        if (!statusText.getText().equals("New Request")) {

            JOptionPane.showMessageDialog(null, new JLabel("Request can not  be rejected!!!!"), "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            for (Donor_Req donorRequest : system.getDonorRequestDir().getDonor_Req_List()) {

                if (donorRequest.getName().equals(nameText.getText())) {
                    statusText.setText("Rejected");
                    donorRequest.setStatus("Rejected");
                }
            }
            dB4OUtil.storeSystem(system);
            viewRequestTable();
            JOptionPane.showMessageDialog(null, new JLabel("Request has been rejected successfully !!!!"));

        }
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_reject_button

    private void lastDaySymptomsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastDaySymptomsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastDaySymptomsTextActionPerformed

    private void followUpTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followUpTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_followUpTestActionPerformed

    private void symptomsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symptomsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symptomsTextActionPerformed

    private void dobDateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dobDateFieldFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_dobDateFieldFocusLost

    private void dobDateFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobDateFieldMouseExited
  
    }//GEN-LAST:event_dobDateFieldMouseExited

    private void dobDateFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobDateFieldMousePressed

    }//GEN-LAST:event_dobDateFieldMousePressed

    private void dobDateFielduDobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobDateFielduDobKeyTyped
        // TODO add your handling code here:
        System.out.println("date");     
    }//GEN-LAST:event_dobDateFielduDobKeyTyped

    private void curedDateFieldUCovidCuredDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_curedDateFieldUCovidCuredDateKeyTyped
    

    }//GEN-LAST:event_curedDateFieldUCovidCuredDateKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageText;
    private javax.swing.JTextField bloodText;
    private javax.swing.JButton button_Approve;
    private javax.swing.JButton button_Details;
    private javax.swing.JButton button_Reject;
    private javax.swing.JTextField cityText;
    private javax.swing.JTextField contactText;
    private com.toedter.calendar.JDateChooser curedDateField;
    private com.toedter.calendar.JDateChooser diagnosedDateField;
    private com.toedter.calendar.JDateChooser dobDateField;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField followUpTest;
    private javax.swing.JTextField genderText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField labConfirmationText;
    private javax.swing.JTextField lastDaySymptomsText;
    private com.toedter.calendar.JDateChooser lastDonationDateField;
    private javax.swing.JLabel lblProfilePicture;
    private javax.swing.JTextField nameText;
    private javax.swing.JTable requestTable;
    private javax.swing.JTextField stateText;
    private javax.swing.JTextField statusText;
    private javax.swing.JTextField streetText;
    private javax.swing.JTextField symptomsText;
    private javax.swing.JTextField uidText;
    private javax.swing.JTextField zipText;
    // End of variables declaration//GEN-END:variables
}
