/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Admin;
import Plasma_DB4OUtil.DB4OUtil;
import Plasma.EcoSystem;
import Plasma_Employee.Employee;
import Plasma_Enterprise.Enterprise;
import Plasma_Network_Cities.Network_Cities;
import Plasma_Association.Association;
import Plasma_Role.Role;
import Plasma_User_Account.User_Acc;
import HomePages.TableFormat;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RST
 */
public class Manage_User_Account_JPanel extends javax.swing.JPanel {

    //Creates new form Manage_User_Account
    
    private JPanel container;
    private Enterprise ent;
    private EcoSystem sys;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public Manage_User_Account_JPanel(JPanel container, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.ent = enterprise;
        this.container = container;
        this.sys = system;

        enterpriseNameTextField1.setText(enterprise.getName());
        //get all the user account values and display in the combo box
        
        popAssociationComboBox();
        userJTable.getTableHeader().setDefaultRenderer(new TableFormat());
        //populate the table with user data
        popDataTable();
    }

    public void popAssociationComboBox() {
        associationJComboBox.removeAllItems();

        for (Association a : ent.getAssociationDirectory().getAssociationList()) {
            associationJComboBox.addItem(a);
        }
    }

    public void populateEmployeeComboBox(Association organization) {
        employeeJComboBox.removeAllItems();

        for (Employee employee : organization.getEmpDir().getEmpList()) {
            employeeJComboBox.addItem(employee);
        }
    }

    private void populateRoleComboBox(Association organization) {
        roleJComboBox.removeAllItems();
        for (Role role : organization.getSupportedRole()) {
            roleJComboBox.addItem(role);
        }
    }

    public void popDataTable() {

        DefaultTableModel model = (DefaultTableModel) userJTable.getModel();

        model.setRowCount(0);

        for (Association organization : ent.getAssociationDirectory().getAssociationList()) {
            for (User_Acc ua : organization.getUserAccDir().getUser_Account_List()) {
                Object row[] = new Object[3];
                row[0] = ua.getEmployee();
                row[1] = ua.getRole();
                row[2] = ua;
                ((DefaultTableModel) userJTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nameSeparator = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        nameSeparator1 = new javax.swing.JSeparator();
        createUserJButton = new javax.swing.JButton();
        nameJTextField = new javax.swing.JTextField();
        passwordJTextField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        associationJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        employeeJComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        roleJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        nameSeparator4 = new javax.swing.JSeparator();
        enterpriseNameTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        userJTable = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 90, 50));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("USER MANAGEMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1806, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1830, -1));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 400));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("EMPLOYEE CREDENTIALS ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 468, 36));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("USERNAME:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 21));

        nameSeparator.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(nameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 290, 10));

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PASSWORD:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 160, 26));

        nameSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(nameSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 290, 10));

        createUserJButton.setBackground(new java.awt.Color(31, 31, 31));
        createUserJButton.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        createUserJButton.setText("CREATE");
        createUserJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_User(evt);
            }
        });
        jPanel2.add(createUserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 110, 35));

        nameJTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        nameJTextField.setBorder(null);
        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 290, 30));

        passwordJTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        passwordJTextField.setBorder(null);
        passwordJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 290, 30));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ORGANIZATION:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 220, -1));

        associationJComboBox.setBackground(new java.awt.Color(0, 0, 0));
        associationJComboBox.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        associationJComboBox.setBorder(null);
        associationJComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                associationJComboBoxItemStateChanged(evt);
            }
        });
        associationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationJComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(associationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 160, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMPLOYEE:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 200, 30));

        employeeJComboBox.setBackground(new java.awt.Color(0, 0, 0));
        employeeJComboBox.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jPanel2.add(employeeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 160, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ROLE:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 170, 40));

        roleJComboBox.setBackground(new java.awt.Color(0, 0, 0));
        roleJComboBox.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jPanel2.add(roleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 160, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 470, 510));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setText("ENTERPRISE:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, 30));

        nameSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        add(nameSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 230, 10));

        enterpriseNameTextField1.setBackground(new java.awt.Color(0, 0, 0));
        enterpriseNameTextField1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        enterpriseNameTextField1.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseNameTextField1.setBorder(null);
        add(enterpriseNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 230, 30));

        userJTable.setBackground(new java.awt.Color(102, 0, 102));
        userJTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 204)));
        userJTable.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        userJTable.setForeground(new java.awt.Color(255, 255, 255));
        userJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMPLOYEE", "ROLE", "USER NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userJTable.setFocusable(false);
        userJTable.setGridColor(new java.awt.Color(0, 0, 0));
        userJTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        userJTable.setRowHeight(30);
        userJTable.setShowVerticalLines(false);
        jScrollPane2.setViewportView(userJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 640, 310));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 222, 0, 160));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 330, 20));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, -1, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, -1, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 180, -1, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void create_User(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_User

        //validate all the selected fields if not selected
        if (associationJComboBox.getSelectedItem().equals(null)) {
            associationJComboBox.setBorder(BorderFactory.createLineBorder(Color.RED));
            associationJComboBox.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Please select an Organization");
        } else if (employeeJComboBox.getSelectedItem().equals(null)) {
            employeeJComboBox.setBorder(BorderFactory.createLineBorder(Color.RED));
            employeeJComboBox.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Please select an Employee");
        } else if (roleJComboBox.getSelectedItem().equals(null)) {
            roleJComboBox.setBorder(BorderFactory.createLineBorder(Color.RED));
            roleJComboBox.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Please select a Role");
        } else if (nameJTextField.getText().isEmpty()) {
            nameJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            nameJTextField.setForeground(Color.red);

            JOptionPane.showMessageDialog(null, new JLabel("Usename cannot be blank!!!"), "Error", JOptionPane.ERROR_MESSAGE);
        } else if (passwordJTextField.getText().length() < 4) {
            passwordJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            passwordJTextField.setForeground(Color.red);

            JOptionPane.showMessageDialog(null, new JLabel("Password should atleast have 4 digits!!!!!"), "Error", JOptionPane.ERROR_MESSAGE);

        } else if (!check_UserIdExists(nameJTextField.getText())) {

            JOptionPane.showMessageDialog(null, new JLabel("Username already exits!!!!!!"), "Error", JOptionPane.ERROR_MESSAGE);

        } 
        //create and add user
        else {
            String userName = nameJTextField.getText();
            String pass = passwordJTextField.getText();
            Association a = (Association) associationJComboBox.getSelectedItem();
            Employee employee = (Employee) employeeJComboBox.getSelectedItem();
            Role role = (Role) roleJComboBox.getSelectedItem();
            a.getUserAccDir().create_User_Account(userName, pass, employee, role);
            popDataTable();
            JOptionPane.showMessageDialog(null, new JLabel("Successfully created user account!!!!!"));//, "Error", JOptionPane.ERROR_MESSAGE);
            dB4OUtil.storeSystem(sys);
            nameJTextField.setText("");
            passwordJTextField.setText("");
        }

    }//GEN-LAST:event_create_User
    //check if the user exists
    private boolean check_UserIdExists(String userName) {
        if (sys.getUserAccDir().check_If_Username_Is_Unique(userName)) {
            if (sys.getUserAccDir().check_If_Username_Is_Unique(userName)) {
                for (Network_Cities network : sys.getCityList()) {
                    for (Enterprise enterprise : network.getEnterprise_Dir().getEnt_List()) {
                        if (enterprise.getUserAccDir().check_If_Username_Is_Unique(userName)) {
                            if (enterprise.getAssociationDirectory().getAssociationList().size() > 0) {
                                for (Association a : enterprise.getAssociationDirectory().getAssociationList()) {
                                    if (a.getUserAccDir().check_If_Username_Is_Unique(userName)) {
                                        return true;
                                    } else {
                                        return false;
                                    }
                                }
                            } else {
                                return true;
                            }
                        } else {
                            return false;
                        }
                    }
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
        return false;
    }
    private void associationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationJComboBoxActionPerformed
        Association a = (Association) associationJComboBox.getSelectedItem();
        if (a != null) {
            populateEmployeeComboBox(a);
            populateRoleComboBox(a);
        }
    }//GEN-LAST:event_associationJComboBoxActionPerformed

    //back button pressed
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void associationJComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_associationJComboBoxItemStateChanged
        // TODO add your handling code here:

        Association a = (Association) associationJComboBox.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) userJTable.getModel();
        model.setRowCount(0);
        for (User_Acc ua : a.getUserAccDir().getUser_Account_List()) {
            Object row[] = new Object[3];
            row[0] = ua.getEmployee();
            row[1] = ua.getRole();
            row[2] = ua;
            ((DefaultTableModel) userJTable.getModel()).addRow(row);
        }
    }//GEN-LAST:event_associationJComboBoxItemStateChanged

    private void passwordJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordJTextFieldActionPerformed

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox associationJComboBox;
    private javax.swing.JButton createUserJButton;
    private javax.swing.JComboBox employeeJComboBox;
    private javax.swing.JTextField enterpriseNameTextField1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JSeparator nameSeparator1;
    private javax.swing.JSeparator nameSeparator4;
    private javax.swing.JPasswordField passwordJTextField;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JTable userJTable;
    // End of variables declaration//GEN-END:variables
}
