/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Admin;
import Plasma_DB4OUtil.DB4OUtil;
import Plasma.EcoSystem;
import Plasma_Enterprise.Enterprise;
import static Plasma_Enterprise.Enterprise.EnterpriseType.CovidCentre;
import static Plasma_Enterprise.Enterprise.EnterpriseType.Government;
import static Plasma_Enterprise.Enterprise.EnterpriseType.Legal;
import static Plasma_Enterprise.Enterprise.EnterpriseType.PlasmaBank;
import Plasma_Association.Association;
import Plasma_Association.Association.CovidCentreType;
import Plasma_Association.Association.GovernmentType;
import Plasma_Association.Association.LegalType;
import Plasma_Association.Association.PlasmaBankType;
import Plasma_Association.Association.Type;
import Plasma_Association.Association_Dir;
import HomePages.TableFormat;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RST
 */
public class Manage_Association_JPanel extends javax.swing.JPanel {

    private Association_Dir dir;
    private JPanel process_container;
    private Enterprise ent;
    EcoSystem sys;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    //Creates new form Manage Organization     
    public Manage_Association_JPanel(JPanel userProcessContainer, Association_Dir dir, Enterprise ent, EcoSystem system) {
        initComponents();
        this.process_container = userProcessContainer;
        this.dir = dir;
        this.ent = ent;
        this.sys = system;
        organizationJTable.getTableHeader().setDefaultRenderer(new TableFormat());
        enterpriseNameTextField1.setText(ent.getName());
        populateTable();
        populateCombo();
    }
    
    //used to opulate combo box
    private void populateCombo() {
        organizationJComboBox.removeAllItems();
        System.out.println(ent.getEnterprise_type());
        System.out.println(ent.getEnterprise_type().toString().equals(PlasmaBank.toString()));
        if (ent.getEnterprise_type().toString().equals(Legal.toString())) {
            for (Association.LegalType legalType : Association.LegalType.values()) {
                if (legalType.getValue().equals(Association.LegalType.LegalOfficer.getValue())) {
                    organizationJComboBox.addItem(legalType);
                }
            }
        } else if (ent.getEnterprise_type().toString().equals(PlasmaBank.toString())) {
            System.out.println("1");
            for (Association.PlasmaBankType plasmaType : Association.PlasmaBankType.values()) {
                System.out.println("1");
                System.out.println(plasmaType.getValue());
                System.out.println(Association.PlasmaBankType.PlasmaBank.getValue());
                if (plasmaType.getValue().equals(Association.PlasmaBankType.PlasmaBank.getValue())) {
                    organizationJComboBox.addItem(plasmaType);
                }
            }
        } else if (ent.getEnterprise_type().toString().equals(CovidCentre.toString())) {
            for (Association.CovidCentreType covidType : Association.CovidCentreType.values()) {
                if (covidType.getValue().equals(Association.CovidCentreType.CovidCentre.getValue())) {
                    organizationJComboBox.addItem(covidType);
                }
            }
        } else if (ent.getEnterprise_type().toString().equals(Government.toString())) {
            for (Association.GovernmentType govtType : Association.GovernmentType.values()) {
                if (govtType.getValue().equals(Association.GovernmentType.Government.getValue())) {
                    organizationJComboBox.addItem(govtType);
                }
            }
        } else {
            for (Association.Type type : Association.Type.values()) {
                if (type.getValue().equals(Association.Type.SystemCoordinator.getValue())
                        || type.getValue().equals(Association.Type.Doctor.getValue())
                        || type.getValue().equals(Association.Type.Pathologist.getValue())) {
                    organizationJComboBox.addItem(type);
                }
            }

        }
    }

    //used to populate table
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        model.setRowCount(0);
        for (Association organization : dir.getAssociationList()) {
            Object[] row = new Object[2];
            row[0] = organization.getName();
            row[1] = organization.getFirstName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOrgRealName = new javax.swing.JTextField();
        nameSeparator = new javax.swing.JSeparator();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        nameSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameSeparator4 = new javax.swing.JSeparator();
        enterpriseNameTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(102, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationJTable.setBackground(new java.awt.Color(102, 0, 102));
        organizationJTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 204)));
        organizationJTable.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        organizationJTable.setForeground(new java.awt.Color(255, 255, 255));
        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORGANIZATION TYPE", "ORGANIZATION NAME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        organizationJTable.setGridColor(new java.awt.Color(0, 0, 0));
        organizationJTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        organizationJTable.setRowHeight(30);
        organizationJTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(organizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 720, 360));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, 46));

        panel1.setBackground(new java.awt.Color(102, 0, 102));
        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204)));
        panel1.setPreferredSize(new java.awt.Dimension(250, 400));
        panel1.setRequestFocusEnabled(false);
        panel1.setVerifyInputWhenFocusTarget(false);
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CREATE ORANIZATION");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 328, 36));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ORGANIZATION NAME");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, 26));

        txtOrgRealName.setBackground(new java.awt.Color(0, 0, 0));
        txtOrgRealName.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txtOrgRealName.setForeground(new java.awt.Color(255, 255, 255));
        txtOrgRealName.setBorder(null);
        txtOrgRealName.setCaretColor(new java.awt.Color(30, 59, 92));
        txtOrgRealName.setOpaque(false);
        txtOrgRealName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOrgRealNameFocusGained(evt);
            }
        });
        txtOrgRealName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgRealNameActionPerformed(evt);
            }
        });
        panel1.add(txtOrgRealName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 312, 290, 30));

        nameSeparator.setForeground(new java.awt.Color(0, 0, 0));
        panel1.add(nameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 280, 10));

        organizationJComboBox.setBackground(new java.awt.Color(0, 0, 0));
        organizationJComboBox.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        organizationJComboBox.setForeground(new java.awt.Color(255, 255, 255));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        panel1.add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 261, 40));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECT ORGANIZATION TYPE ");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 300, -1));

        addJButton.setBackground(new java.awt.Color(31, 31, 31));
        addJButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        addJButton.setText("ADD ORGANIZATION");
        addJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_association(evt);
            }
        });
        panel1.add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 190, 40));

        nameSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panel1.add(nameSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 290, 10));

        add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 400, 460));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ORGANIZATION MANAGEMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1656, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setText("ENTERPRISE:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        nameSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        add(nameSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 240, 10));

        enterpriseNameTextField1.setBackground(new java.awt.Color(0, 0, 0));
        enterpriseNameTextField1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        enterpriseNameTextField1.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseNameTextField1.setBorder(null);
        add(enterpriseNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void add_association(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_association

        String check = "";

        if (txtOrgRealName.getText().isEmpty()) {
            txtOrgRealName.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtOrgRealName.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "Association name cannot be empty!");
            check = "do not go further!";
            return;
        }

        for (Association association : dir.getAssociationList()) {

            if (association.getName().equals(txtOrgRealName.getText())) {

                JOptionPane.showMessageDialog(null, "Association name already exists!");
                check = "do not go further!";
                return;
            }
        }

        // Main Process after validation checks
        if (check.equals("")) {
            if (ent.getEnterprise_type().toString().equals(Legal.toString())) {
                dir.createLegalAssociation((LegalType) organizationJComboBox.getSelectedItem(), txtOrgRealName.getText());
            } else if (ent.getEnterprise_type().toString().equals(Government.toString())) {
                dir.createGovernmentAssociation((GovernmentType) organizationJComboBox.getSelectedItem(), txtOrgRealName.getText());
            } else if (ent.getEnterprise_type().toString().equals(PlasmaBank.toString())) {
                dir.createPlasmaAssociation((PlasmaBankType) organizationJComboBox.getSelectedItem(), txtOrgRealName.getText());
            } else if (ent.getEnterprise_type().toString().equals(CovidCentre.toString())) {
                dir.createCOVIDAssociation((CovidCentreType) organizationJComboBox.getSelectedItem(), txtOrgRealName.getText());
            } else {

                Type type = (Type) organizationJComboBox.getSelectedItem();
                dir.createAssociation(type, txtOrgRealName.getText());
            }
            //if conditions match then populate and display into table
            populateTable();
            JOptionPane.showMessageDialog(null, "Association created successfully!");
            dB4OUtil.storeSystem(sys);

            txtOrgRealName.setText("");
            organizationJComboBox.removeItem(organizationJComboBox.getSelectedItem());
        }
    }//GEN-LAST:event_add_association

    //back button action
    private void back_button(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button
        // TODO add your handling code here:
        process_container.remove(this);
        CardLayout layout = (CardLayout) process_container.getLayout();
        layout.previous(process_container);
    }//GEN-LAST:event_back_button

    private void txtOrgRealNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOrgRealNameFocusGained
        // TODO add your handling code here:
        txtOrgRealName.setText("");
    }//GEN-LAST:event_txtOrgRealNameFocusGained

    private void txtOrgRealNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgRealNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgRealNameActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JTextField enterpriseNameTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JSeparator nameSeparator1;
    private javax.swing.JSeparator nameSeparator4;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField txtOrgRealName;
    // End of variables declaration//GEN-END:variables
}
