/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_COVIDCare_Coordinator;
import Plasma_DB4OUtil.DB4OUtil;
import Plasma.EcoSystem;
import Plasma_Enterprise.Enterprise;
import Plasma_Network_Cities.Network_Cities;
import Plasma_Association.Legal_Officer_Association;
import Plasma_Association.Association;
import Plasma_People.Patient;
import Plasma_User_Account.User_Acc;
import Plasma_Work_Queue.System_Coordinator_Work_Request;
import Plasma_Work_Queue.Work_Req;
import HomePages.TableFormat;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RST
 */
public class Create_Patient_JPanel extends javax.swing.JPanel {

    //Create new form Create_Patient
   
    private EcoSystem system;
    private User_Acc user_Account;
    private Network_Cities network;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    //constructor for create patient
    Create_Patient_JPanel(EcoSystem system, User_Acc userAccount, Network_Cities network) {
        initComponents();        
        this.system = system;
        this.user_Account = userAccount;
        this.network = network;
        populateTable();
        populatePatientTable();
        tblPatient.getTableHeader().setDefaultRenderer(new TableFormat());
        tblRequest.getTableHeader().setDefaultRenderer(new TableFormat());
    }

    //this method displays all the details in the table
    
    private void populatePatientTable() {
        DefaultTableModel dtmA = (DefaultTableModel) tblPatient.getModel();
        dtmA.setRowCount(0);
        Object row[] = new Object[5];
        String line = "";
        String splitBy = ",";
        try {
            //parsing a CSV file into BufferedReader class constructor  
            BufferedReader br = new BufferedReader(new FileReader("RecordforPatients.csv"));
            while ((line = br.readLine()) != null) //returns a Boolean value  
            {
                String[] csv = line.split(splitBy);    // use comma as separator 
                row[0] = csv[0];
                row[1] = csv[1];
                row[2] = csv[2];
                row[3] = csv[3];
                row[4] = csv[4];

                dtmA.addRow(row);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblRequest.getModel();

        dtm.setRowCount(0);

        for (Work_Req request : user_Account.getWorkQueue().getWork_Req_List()) {
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getSummary();
            row[2] = request.getPatient();
            row[3] = request.getPatient().getEmailID();
            row[4] = request.getStatus();
            row[5] = request.getAction_Date();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uidTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        btnCreateReceiver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        chkEmergency = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bloodGroupTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel2.setText("USER ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel3.setText("EMAIL:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        uidTextField.setBackground(new java.awt.Color(0, 0, 0));
        uidTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        uidTextField.setForeground(new java.awt.Color(255, 255, 255));
        uidTextField.setEnabled(false);
        add(uidTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 212, -1));

        emailTextField.setBackground(new java.awt.Color(0, 0, 0));
        emailTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField.setEnabled(false);
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 212, -1));

        btnCreateReceiver.setBackground(new java.awt.Color(0, 0, 0));
        btnCreateReceiver.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        btnCreateReceiver.setText("CREATE PATIENT/RECEIVER");
        btnCreateReceiver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateReceiver.setEnabled(false);
        btnCreateReceiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_patient(evt);
            }
        });
        add(btnCreateReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 320, 40));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel4.setText("CREATE RECEIVER PROFILE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, -1, -1));

        tblPatient.setBackground(new java.awt.Color(102, 0, 102));
        tblPatient.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblPatient.setForeground(new java.awt.Color(255, 255, 255));
        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UID", "NAME", "EMAIL", "Covid Diagnosed Date", "Blood Group"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatient.setFocusable(false);
        tblPatient.setGridColor(new java.awt.Color(0, 0, 0));
        tblPatient.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblPatient.setRowHeight(30);
        tblPatient.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblPatient);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 970, 230));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel1.setText("COVID PATIENT LIST");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" RECEIVER LIST");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, -1, -1));

        tblRequest.setBackground(new java.awt.Color(102, 0, 102));
        tblRequest.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblRequest.setForeground(new java.awt.Color(255, 255, 255));
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Summary", "Patient Name", "Email ID", "Status", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRequest.setFocusable(false);
        tblRequest.setGridColor(new java.awt.Color(0, 0, 0));
        tblRequest.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblRequest.setRowHeight(30);
        tblRequest.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tblRequest);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 970, 250));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText(" PROFILE CREATION FOR PATIENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 1656, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, -1));

        chkEmergency.setBackground(new java.awt.Color(102, 0, 102));
        chkEmergency.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        chkEmergency.setText("EMERGENCY");
        chkEmergency.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chkEmergency.setEnabled(false);
        add(chkEmergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel6.setText("NAME:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        nameTextField.setBackground(new java.awt.Color(0, 0, 0));
        nameTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(255, 255, 255));
        nameTextField.setEnabled(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 212, -1));

        jButton2.setBackground(new java.awt.Color(31, 31, 31));
        jButton2.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jButton2.setText("VIEW DETAILS");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_details(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 160, 40));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel8.setText("BLOOD GROUP:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        bloodGroupTextField.setBackground(new java.awt.Color(0, 0, 0));
        bloodGroupTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        bloodGroupTextField.setForeground(new java.awt.Color(255, 255, 255));
        bloodGroupTextField.setEnabled(false);
        add(bloodGroupTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 210, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 112, 250, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 112, 310, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 990, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 990, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 1140, -1));
    }// </editor-fold>//GEN-END:initComponents

    //creates new patient
    private void create_patient(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_patient
        // TODO add your handling code here:
        Patient patient = system.getPatientDir().addPatient();
        patient.setReceiverID(uidTextField.getText());
        patient.setName(nameTextField.getText());
        patient.setEmailID((emailTextField.getText()));
        patient.setBlood_Group(bloodGroupTextField.getText());
        patient.setEmergency_Status(chkEmergency.isSelected());
        patient.setStatus("Centre Approved");
        populateTable();
        JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>A new Patinet has been <font color='green'>added</font></I></h2></html>"));
        Work_Req request = new System_Coordinator_Work_Request();
        request.setPatient(patient);
        request.setAction_Date(new Date());
        request.setAssigned("Legal Pool");
        request.setSummary("Requested for Plasma Reception");
        request.setStatus("Assigned to Legal Pool");
        request.setUser_Acc(user_Account);
        Enterprise ent = null;
        Association org = null;

        for (Enterprise enterprise : network.getEnterprise_Dir().getEnt_List()) {
            if (enterprise.getEnterprise_type().toString().equals("Legal")) {

                ent = enterprise;
                System.out.println(enterprise);
                break;
            }
        }

        for (Association a : ent.getAssociationDirectory().getAssociationList()) {
            if (a instanceof Legal_Officer_Association) {
                org = a;
                break;
            }
        }

        if (org != null) {
            org.getWorkQueue().getWork_Req_List().add(request);
            System.out.println(org.getName());
            user_Account.getWorkQueue().getWork_Req_List().add(request);

            dB4OUtil.storeSystem(system);
            populateTable();
            JOptionPane.showMessageDialog(null, new JLabel("Request has been transferred for Legal Approval!!!!"));

        } else {

            JOptionPane.showMessageDialog(null, "No organization present", "Error", JOptionPane.ERROR_MESSAGE);
        }
        chkEmergency.setEnabled(false);
        btnCreateReceiver.setEnabled(false);
        uidTextField.setText("");
        nameTextField.setText("");
        emailTextField.setText("");
        bloodGroupTextField.setText("");
    }//GEN-LAST:event_create_patient
    
    //view all the details of the patient
    
    private void view_details(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_details
        // TODO add your handling code here:

        int selectedRow = tblPatient.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Please select<font color='red'> a row</font> from the<font color='green'> table</I></font></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            uidTextField.setText(String.valueOf(tblPatient.getValueAt(selectedRow, 0)));
            nameTextField.setText(String.valueOf(tblPatient.getValueAt(selectedRow, 1)));
            emailTextField.setText(String.valueOf(tblPatient.getValueAt(selectedRow, 2)));
            bloodGroupTextField.setText(String.valueOf(tblPatient.getValueAt(selectedRow, 4)));
            btnCreateReceiver.setEnabled(true);
            chkEmergency.setEnabled(true);
        }

    }//GEN-LAST:event_view_details

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodGroupTextField;
    private javax.swing.JButton btnCreateReceiver;
    private javax.swing.JCheckBox chkEmergency;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTextField uidTextField;
    // End of variables declaration//GEN-END:variables
}
