/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI_COVIDCare_Coordinator;
import Plasma_DB4OUtil.DB4OUtil;
import Plasma.EcoSystem;
import Plasma_Enterprise.Enterprise;
import Plasma_Network_Cities.Network_Cities;
import Plasma_Association.Legal_Officer_Association;
import Plasma_Association.Association;
import Plasma_People.Patient;
import Plasma_People.Patient_Req;
import Plasma_User_Account.User_Acc;
import Plasma_Work_Queue.System_Coordinator_Work_Request;
import Plasma_Work_Queue.Work_Req;
import HomePages.TableFormat;
import java.awt.Color;
import java.awt.Image;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Akshay
 */
public class Volunteer_Receiver_Request_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerReceiverRequestJPanel
     */
    private  EcoSystem system;
    private Patient_Req  patientRequest;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private User_Acc  userAccount;
    private Network_Cities  network;
    
    public Volunteer_Receiver_Request_JPanel(EcoSystem system, User_Acc userAccount, Network_Cities network) {
        initComponents();
        this.system = system;
        this.userAccount = userAccount;
        this.network = network;
        requestTable.getTableHeader().setDefaultRenderer(new TableFormat());
        populateRequestTable();
    }
  

    private void populateRequestTable(){
        DefaultTableModel dtm = (DefaultTableModel) requestTable.getModel();
        
        dtm.setRowCount(0);
        
         for(Patient_Req patientRequest: system.getPatientRequestDir().getPatient_Req_List()){            
            Object row[] = new Object[4];
            row[0]= patientRequest;
            row[1]= patientRequest.getName();
            row[2]= patientRequest.getContact();
            row[3]= patientRequest.getStatus();
              
            dtm.addRow(row);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonApprove = new javax.swing.JButton();
        buttonReject = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        uidText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        contactText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        genderText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bloodText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        streetText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        stateText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        zipText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        labConfirmationText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        statusText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblProfilePicture = new javax.swing.JLabel();
        dobDateField = new com.toedter.calendar.JDateChooser();
        diagnosedDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonApprove.setBackground(new java.awt.Color(31, 31, 31));
        buttonApprove.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        buttonApprove.setText("APPROVE");
        buttonApprove.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonApprove.setEnabled(false);
        buttonApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApproveActionPerformed(evt);
            }
        });
        add(buttonApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 570, 120, 40));

        buttonReject.setBackground(new java.awt.Color(31, 31, 31));
        buttonReject.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        buttonReject.setText("REJECT");
        buttonReject.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonReject.setEnabled(false);
        buttonReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRejectActionPerformed(evt);
            }
        });
        add(buttonReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 640, 120, 40));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("UID:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 300, -1, -1));

        uidText.setBackground(new java.awt.Color(0, 0, 0));
        uidText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        uidText.setForeground(new java.awt.Color(255, 255, 255));
        add(uidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 300, 180, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("NAME:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, 30));

        nameText.setBackground(new java.awt.Color(0, 0, 0));
        nameText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 190, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("DOB:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setText("AGE:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, -1, 30));

        ageText.setBackground(new java.awt.Color(0, 0, 0));
        ageText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        ageText.setForeground(new java.awt.Color(255, 255, 255));
        ageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextActionPerformed(evt);
            }
        });
        add(ageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, 190, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel16.setText("CONTACT NUMBER:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, -1, -1));

        contactText.setBackground(new java.awt.Color(0, 0, 0));
        contactText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        contactText.setForeground(new java.awt.Color(255, 255, 255));
        add(contactText, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 190, -1));

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel17.setText("EMAIL ID:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, 30));

        emailText.setBackground(new java.awt.Color(0, 0, 0));
        emailText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        emailText.setForeground(new java.awt.Color(255, 255, 255));
        add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 190, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setText("GENDER");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 360, 100, -1));

        genderText.setBackground(new java.awt.Color(0, 0, 0));
        genderText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        genderText.setForeground(new java.awt.Color(255, 255, 255));
        add(genderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 360, 180, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel10.setText("BLOOD GROUP:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, -1, 20));

        bloodText.setBackground(new java.awt.Color(0, 0, 0));
        bloodText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        bloodText.setForeground(new java.awt.Color(255, 255, 255));
        add(bloodText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 120, 180, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setText("COVID DIAGONISE DATE:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 730, -1, 30));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel12.setText("STREET ADDRESS:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 170, -1, -1));

        streetText.setBackground(new java.awt.Color(0, 0, 0));
        streetText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        streetText.setForeground(new java.awt.Color(255, 255, 255));
        add(streetText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 170, 176, -1));

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel13.setText("CITY:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 210, -1, -1));

        cityText.setBackground(new java.awt.Color(0, 0, 0));
        cityText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        cityText.setForeground(new java.awt.Color(255, 255, 255));
        add(cityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 210, 180, -1));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel14.setText("STATE:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, -1, -1));

        stateText.setBackground(new java.awt.Color(0, 0, 0));
        stateText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        stateText.setForeground(new java.awt.Color(255, 255, 255));
        add(stateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 250, 180, -1));

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel15.setText("ZIPCODE:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, -1));

        zipText.setBackground(new java.awt.Color(0, 0, 0));
        zipText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        zipText.setForeground(new java.awt.Color(255, 255, 255));
        add(zipText, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 190, -1));

        jLabel19.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel19.setText("WAS YOUR COVID TEST CONFIRM IN LABORTARY?");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 650, -1, -1));

        jButton3.setBackground(new java.awt.Color(31, 31, 31));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jButton3.setText("VIEW DETAILS");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, 40));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("REQUESTS OF PATIENTS TO HANDLE");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 1556, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, -1));

        labConfirmationText.setBackground(new java.awt.Color(0, 0, 0));
        labConfirmationText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labConfirmationText.setForeground(new java.awt.Color(255, 255, 255));
        add(labConfirmationText, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 680, 210, -1));

        requestTable.setBackground(new java.awt.Color(102, 0, 102));
        requestTable.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        requestTable.setForeground(new java.awt.Color(255, 255, 255));
        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UID", "NAME", "CONTACT", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        requestTable.setFocusable(false);
        requestTable.setGridColor(new java.awt.Color(0, 0, 0));
        requestTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        requestTable.setRowHeight(30);
        requestTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(requestTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 670, 340));

        statusText.setBackground(new java.awt.Color(0, 0, 0));
        statusText.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        statusText.setForeground(new java.awt.Color(255, 255, 255));
        add(statusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, 200, -1));

        jLabel1.setText("Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 11, -1, -1));

        lblProfilePicture.setBackground(new java.awt.Color(0, 0, 0));
        lblProfilePicture.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(lblProfilePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 400, 140, 130));

        dobDateField.setBackground(new java.awt.Color(0, 0, 0));
        dobDateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dobDateField.setForeground(new java.awt.Color(255, 255, 255));
        add(dobDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 190, 30));

        diagnosedDateChooser.setBackground(new java.awt.Color(0, 0, 0));
        diagnosedDateChooser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        diagnosedDateChooser.setForeground(new java.awt.Color(255, 255, 255));
        add(diagnosedDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 730, 170, 30));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("STATUS:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 1500, 10));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 22)); // NOI18N
        jLabel4.setText("COVID HISTORY DETAILS");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel5.setText("BIOGRAPHIC DETAILS");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApproveActionPerformed
        // TODO add your handling code here:
        if( !statusText.getText().equals("New Request"))
            {
                JOptionPane.showMessageDialog(null, new JLabel( "Request can not be approved!!!!"), "Warning", JOptionPane.WARNING_MESSAGE);
           
                
            //    JOptionPane.showMessageDialog(null,"Can Not Approve the Request!");
            }
        
        else
        {
        
        Patient patient = system.getPatientDir().addPatient();
        patient.setName(nameText.getText());
        patient.setMobile((contactText.getText()));  
        
        patient.setReceiverID(uidText.getText()); // UID, receiverID
        patient.setName(nameText.getText()); // Name
       
       
        
        patient.setAge(Integer.parseInt(ageText.getText())); // Age
        patient.setGender(genderText.getText()); // gender
        patient.setBlood_Group(bloodText.getText()); // Blood group
        patient.setAddress(streetText.getText()); // streetAddress
        patient.setCity(cityText.getText()); // city
        patient.setState(stateText.getText()); // state
        patient.setZipCode(Integer.parseInt(zipText.getText())); // zipCode
        patient.setMobile((contactText.getText())); // contact
        patient.setEmailID(emailText.getText()); // emailID
        patient.setStatus("Centre Approved"); // status
        patient.setLabConfirmation(true); //  labConfirmation
      
        
        for(Patient_Req  patientRequest: system.getPatientRequestDir().getPatient_Req_List()){                      
        
            if(patientRequest.getReceiverID().equals(uidText.getText())){
            patientRequest.setStatus("Centre Approved");
            dB4OUtil.storeSystem(system);
            }
        }



        // WORK REQUEST
        
        Work_Req  request = new System_Coordinator_Work_Request();
        
        request.setPatient(patient);
        request.setAction_Date(new Date());
        request.setAssigned("Legal Pool");
        request.setSummary("Requested for Plasma Reception");
        request.setStatus("Assigned to Legal Pool");
        
        request.setUser_Acc(userAccount);
       
        Enterprise ent = null;
        Association org = null;
        
        for (Enterprise enterprise : network.getEnterprise_Dir().getEnt_List()) {
            if (enterprise.getEnterprise_type().toString().equals("Legal")) {
            
                ent = enterprise;
                System.out.println(enterprise);
                break;
            }
        }
        
        
       
        for (Association organization : ent.getAssociationDirectory().getAssociationList()) {
            if(organization instanceof Legal_Officer_Association) {
                org = organization;
                break;
            }
        }
        
        if (org != null) {
            org.getWorkQueue().getWork_Req_List().add(request);
            System.out.println(org.getName());
            userAccount.getWorkQueue().getWork_Req_List().add(request);
            //user.addUserRequest(request);
            
            dB4OUtil.storeSystem(system);
            populateRequestTable();
            JOptionPane.showMessageDialog(null, new JLabel(  "Successfully Approved Request  !!!!!"));
           
            //JOptionPane.showMessageDialog(null,"Request Sent Successfully", "Info", JOptionPane.INFORMATION_MESSAGE);
            
        } else {
        
         JOptionPane.showMessageDialog(null, "No organization present", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
        
        
        
        statusText.setText("Centre Approved");
        dB4OUtil.storeSystem(system);
        populateRequestTable();
      //  JOptionPane.showMessageDialog(null,"New patient has been added!");
        
        }
    }//GEN-LAST:event_buttonApproveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        
        int selectedRow = requestTable.getSelectedRow();
        if(selectedRow < 0){
            
             JOptionPane.showMessageDialog(null, new JLabel(  "Please make the selection from the table!!!!!"), "Warning", JOptionPane.WARNING_MESSAGE);
           
            
            //JOptionPane.showMessageDialog(null,"Please select a row from the table first to View Details!","Warning!",JOptionPane.WARNING_MESSAGE);
        }
        else{
       //display the details 
            patientRequest = (Patient_Req) requestTable.getValueAt(selectedRow, 0);
            populateRequestDetails(patientRequest);
            buttonApprove.setEnabled(true);
            buttonReject.setEnabled(true);
            
            if(Integer.parseInt(ageText.getText()) < 18)
            {
            ageText.setBorder(BorderFactory.createLineBorder(Color.RED));
            ageText.setForeground(Color.red);
            }
            if(labConfirmationText.getText().equals("false"))
            {
            labConfirmationText.setBorder(BorderFactory.createLineBorder(Color.RED));
            labConfirmationText.setForeground(Color.red);
            }
            
            
             dB4OUtil.storeSystem(system);
            
            
        }
    }
        
        private void populateRequestDetails(Patient_Req patientRequest){
            uidText.setText(patientRequest.getReceiverID());
            nameText.setText(patientRequest.getName());
            dobDateField.setDate(patientRequest.getDob());
            diagnosedDateChooser.setDate(patientRequest.getCovidDiagnosedDate());
            ageText.setText(String.valueOf(patientRequest.getAge()));
            genderText.setText(patientRequest.getGender());
            bloodText.setText(patientRequest.getBloodGroup());
            streetText.setText(patientRequest.getStreetAddress());
            cityText.setText(patientRequest.getCity());
            stateText.setText(patientRequest.getState());
            zipText.setText(String.valueOf(patientRequest.getZipCode()));
            contactText.setText(String.valueOf(patientRequest.getContact()));
            emailText.setText(patientRequest.getEmailID());
            statusText.setText(patientRequest.getStatus());
            
            labConfirmationText.setText(String.valueOf(patientRequest.isLabConfirmation()));
            
            
            
            
             if(patientRequest.getdP() !=null){
            //Working line
            byte[] JLabelpictureLabel = patientRequest.getdP();
            ImageIcon i = setPicturebyte(JLabelpictureLabel);
            lblProfilePicture.setIcon(i);
            }
            else{
            System.err.println("No Image");
            }
             
             
            uidText.setEditable(false);
            nameText.setEditable(false);
            ageText.setEditable(false);
            genderText.setEditable(false);
            bloodText.setEditable(false);
            streetText.setEditable(false);
            cityText.setEditable(false);
            stateText.setEditable(false);
            zipText.setEditable(false);
            contactText.setEditable(false);
            emailText.setEditable(false);
            statusText.setEditable(false);
            labConfirmationText.setEditable(false);     
            diagnosedDateChooser.setEnabled(false);
            dobDateField.setEnabled(false);
                   
             
            
        }
        
        
        private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  

    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRejectActionPerformed
        // TODO add your handling code here:
        
       if(!statusText.getText().equals("New Request"))
                  {
                      JOptionPane.showMessageDialog(null, new JLabel(  "Sorry Request cannot be rejected!!!!!1"), "Warning", JOptionPane.WARNING_MESSAGE);
          
                     // JOptionPane.showMessageDialog(null,"Can Not Reject the Request!");
        }
       else{
        for(Patient_Req patientRequest: system.getPatientRequestDir().getPatient_Req_List()){                      
        
            if(patientRequest.getName().equals(nameText.getText())){
            statusText.setText("Rejected");
            patientRequest.setStatus("Rejected");
            }}
        
        dB4OUtil.storeSystem(system);   
        populateRequestTable();
        
         JOptionPane.showMessageDialog(null, new JLabel("Successfully Rejected the request!!!!!"));
        
        //JOptionPane.showMessageDialog(null,"Rejected the Patient's Request!");
        }
       
        
    }//GEN-LAST:event_buttonRejectActionPerformed

    private void ageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageText;
    private javax.swing.JTextField bloodText;
    private javax.swing.JButton buttonApprove;
    private javax.swing.JButton buttonReject;
    private javax.swing.JTextField cityText;
    private javax.swing.JTextField contactText;
    private com.toedter.calendar.JDateChooser diagnosedDateChooser;
    private com.toedter.calendar.JDateChooser dobDateField;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField genderText;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField labConfirmationText;
    private javax.swing.JLabel lblProfilePicture;
    private javax.swing.JTextField nameText;
    private javax.swing.JTable requestTable;
    private javax.swing.JTextField stateText;
    private javax.swing.JTextField statusText;
    private javax.swing.JTextField streetText;
    private javax.swing.JTextField uidText;
    private javax.swing.JTextField zipText;
    // End of variables declaration//GEN-END:variables
}
