/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Pathologist;
import Plasma_Enterprise.Enterprise;
import Plasma_Association.Pathologist_Association;
import Plasma_User_Account.User_Acc;
import java.util.Date;
/**
 *
 * @author RST
 */
public class Manage_Pathologist_Profile extends javax.swing.JPanel {

    //Creates new form Manage Doctor Profile     
    private User_Acc user;
    private Enterprise enterprise;
    private Pathologist_Association pathologist;

    public Manage_Pathologist_Profile(User_Acc userAccount, Pathologist_Association pathoOrganization, Enterprise enterprise) {
        initComponents();
        this.user = userAccount;
        this.enterprise = enterprise;
        this.pathologist = pathoOrganization;
        pop_table();
    }

    private void pop_table() {
        gender_comboBox.removeAllItems();
        gender_comboBox.addItem("MALE");
        gender_comboBox.addItem("FEMALE");
        txtAddress.setText(user.getEmployee().getAddress());
        txtCity.setText(user.getEmployee().getCity());
        txtContact.setText(String.valueOf(user.getEmployee().getMobile()));
        txtDOB.setText(String.valueOf(user.getEmployee().getDob()));
        txtName.setText(user.getEmployee().getName());
        txtSpecialization.setText(user.getEmployee().getSpecialization());
        txtState.setText(user.getEmployee().getState());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtSpecialization = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        gender_comboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTACT:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADDRESS:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CITY:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STATE:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GENDER:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DOB:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SPECIALIZATION:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtName.setBackground(new java.awt.Color(0, 0, 0));
        txtName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 44, 146, -1));

        txtContact.setBackground(new java.awt.Color(0, 0, 0));
        txtContact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtContact.setForeground(new java.awt.Color(255, 255, 255));
        add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 74, 146, -1));

        txtAddress.setBackground(new java.awt.Color(0, 0, 0));
        txtAddress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(255, 255, 255));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 104, 146, -1));

        txtCity.setBackground(new java.awt.Color(0, 0, 0));
        txtCity.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCity.setForeground(new java.awt.Color(255, 255, 255));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 134, 146, -1));

        txtState.setBackground(new java.awt.Color(0, 0, 0));
        txtState.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtState.setForeground(new java.awt.Color(255, 255, 255));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 164, 146, -1));

        txtSpecialization.setBackground(new java.awt.Color(0, 0, 0));
        txtSpecialization.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtSpecialization.setForeground(new java.awt.Color(255, 255, 255));
        add(txtSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 146, -1));

        txtDOB.setBackground(new java.awt.Color(0, 0, 0));
        txtDOB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDOB.setForeground(new java.awt.Color(255, 255, 255));
        add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 233, 146, -1));

        btnSave.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_button(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 356, 90, 30));

        gender_comboBox.setBackground(new java.awt.Color(0, 0, 0));
        gender_comboBox.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        gender_comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(gender_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 197, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EMAIL:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        txtEmail.setBackground(new java.awt.Color(0, 0, 0));
        txtEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 146, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 70, 56));
    }// </editor-fold>//GEN-END:initComponents

    private void save_button(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_button
        user.getEmployee().setCity(txtCity.getText());
        user.getEmployee().setMobile(txtContact.getText());
        user.getEmployee().setDob(new Date(txtDOB.getText()));
        user.getEmployee().setGender((String) gender_comboBox.getSelectedItem());
        user.getEmployee().setAddress(txtAddress.getText());

        user.getEmployee().setState(txtCity.getText());
        user.getEmployee().setSpecialization(txtSpecialization.getText());


    }//GEN-LAST:event_save_button


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox gender_comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSpecialization;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables
}
