/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_System_Admin_Work_Area;

import Plasma_DB4OUtil.DB4OUtil;
import Plasma.EcoSystem;
import Plasma_Employee.Employee;
import Plasma_Enterprise.Enterprise;
import Plasma_Network_Cities.Network_Cities;
import Plasma_Association.Association;
import Plasma_Role.Admin;
import Plasma_User_Account.User_Acc;
import HomePages.TableFormat;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RST
 */
public class Manage_Enterprise_Admin_JPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Enterprise enterprise;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    //Creates new form ManageEnterprise
    public Manage_Enterprise_Admin_JPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;

        enterprise_JTable.getTableHeader().setDefaultRenderer(new TableFormat());
        tbl_AdminUserName.getTableHeader().setDefaultRenderer(new TableFormat());
        populate_Table();

    }

    private boolean check_UserId_Exists(String userName) {
        if (system.getUserAccDir().check_If_Username_Is_Unique(userName)) {
            if (system.getUserAccDir().check_If_Username_Is_Unique(userName)) {
                for (Network_Cities network : system.getCityList()) {
                    for (Enterprise enterprise : network.getEnterprise_Dir().getEnt_List()) {
                        if (enterprise.getUserAccDir().check_If_Username_Is_Unique(userName)) {
                            if (enterprise.getAssociationDirectory().getAssociationList().size() > 0) {
                                for (Association organization : enterprise.getAssociationDirectory().getAssociationList()) {
                                    if (organization.getUserAccDir().check_If_Username_Is_Unique(userName)) {
                                        return true;

                                    } else {
                                        return false;
                                    }

                                }
                            } else {
                                return true;
                            }
                        } else {
                            return false;

                        }
                    }
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
        return false;
    }

    private void populate_Table() {
        DefaultTableModel table = (DefaultTableModel) enterprise_JTable.getModel();

        table.setRowCount(0);
        for (Network_Cities city : system.getCityList()) {
            for (Enterprise enterprise : city.getEnterprise_Dir().getEnt_List()) {

                Object[] row = new Object[6];
                row[0] = enterprise;
                row[1] = enterprise.getEnterprise_type().getValue();
                row[2] = city.getCity_name();
                row[5] = enterprise.getEmail();
                row[3] = enterprise.getMobile();
                row[4] = enterprise.getPincode();

                table.addRow(row);

            }
        }
    }

    private void populate_AdminTable(Enterprise enterprise1) {

        DefaultTableModel table = (DefaultTableModel) tbl_AdminUserName.getModel();

        table.setRowCount(0);

        for (User_Acc user : enterprise1.getUserAccDir().getUser_Account_List()) {
            Object[] row = new Object[3];
            row[0] = enterprise;
            row[1] = user.getEmployee().getName();
            row[2] = user.getUsername();
            table.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_AdminUserName = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_AdminName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_UserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();
        btnCreateAdmin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterprise_JTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(1550, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(1550, 70));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADMIN ENTERPRISE MANAGEMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1386, Short.MAX_VALUE)
                .addGap(124, 124, 124))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, -1));

        tbl_AdminUserName.setBackground(new java.awt.Color(0, 0, 0));
        tbl_AdminUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 204)));
        tbl_AdminUserName.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tbl_AdminUserName.setForeground(new java.awt.Color(255, 255, 255));
        tbl_AdminUserName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Admin Name", "UserName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_AdminUserName.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_AdminUserName.setRowHeight(30);
        tbl_AdminUserName.setShowVerticalLines(false);
        jScrollPane3.setViewportView(tbl_AdminUserName);
        if (tbl_AdminUserName.getColumnModel().getColumnCount() > 0) {
            tbl_AdminUserName.getColumnModel().getColumn(0).setResizable(false);
            tbl_AdminUserName.getColumnModel().getColumn(1).setResizable(false);
            tbl_AdminUserName.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, 660, 280));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 400));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CREATE ADMIN");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENTERPRISE NAME:");

        txt_Name.setBackground(new java.awt.Color(0, 0, 0));
        txt_Name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Name.setForeground(new java.awt.Color(255, 255, 255));
        txt_Name.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADMIN NAME:");

        txt_AdminName.setBackground(new java.awt.Color(0, 0, 0));
        txt_AdminName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_AdminName.setForeground(new java.awt.Color(255, 255, 255));
        txt_AdminName.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER NAME:");

        txt_UserName.setBackground(new java.awt.Color(0, 0, 0));
        txt_UserName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_UserName.setForeground(new java.awt.Color(255, 255, 255));
        txt_UserName.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD:");

        txt_Password.setBackground(new java.awt.Color(0, 0, 0));
        txt_Password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Password.setForeground(new java.awt.Color(255, 255, 255));
        txt_Password.setEnabled(false);

        btnCreateAdmin.setBackground(new java.awt.Color(31, 31, 31));
        btnCreateAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreateAdmin.setText("CREATE ADMIN");
        btnCreateAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_admin(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(txt_AdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnCreateAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_AdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnCreateAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 380, 400));

        enterprise_JTable.setBackground(new java.awt.Color(0, 0, 0));
        enterprise_JTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 204)));
        enterprise_JTable.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        enterprise_JTable.setForeground(new java.awt.Color(255, 255, 255));
        enterprise_JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Enterprise Type", "Network", "Contact", "Zipcode", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterprise_JTable.setGridColor(new java.awt.Color(0, 0, 0));
        enterprise_JTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        enterprise_JTable.setRowHeight(30);
        enterprise_JTable.setShowVerticalLines(false);
        enterprise_JTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterprise_JTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(enterprise_JTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 800, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void create_admin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_admin

        int selectedRow = enterprise_JTable.getSelectedRow();

        if (txt_AdminName.getText().isEmpty()) {
            txt_AdminName.setBorder(BorderFactory.createLineBorder(Color.RED));
            txt_AdminName.setForeground(Color.red);
        }

        if (txt_UserName.getText().isEmpty()) {
            txt_UserName.setBorder(BorderFactory.createLineBorder(Color.RED));
            txt_UserName.setForeground(Color.red);
        }

        if (txt_Password.getText().isEmpty()) {
            txt_Password.setBorder(BorderFactory.createLineBorder(Color.RED));
            txt_Password.setForeground(Color.red);
        }

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Please select<font color='red'> a row</font> to process! </I></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (txt_UserName.getText().isEmpty() || txt_AdminName.getText().isEmpty() || txt_Password.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>All fields are</I><font color='red'> mandatory</font>!</h2></html>"), "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!check_UserId_Exists(txt_UserName.getText())) {
            txt_UserName.setBorder(BorderFactory.createLineBorder(Color.RED));
            txt_UserName.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>User name</I><font color='red'> already</font> present!</h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (txt_Password.getText().length() < 4) {
            txt_Password.setBorder(BorderFactory.createLineBorder(Color.RED));
            txt_Password.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><font color='red'><I>Password</I></font> should be<font color='green'> more than 4 digit!</font>!</h2></html>"), "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            String uname = txt_UserName.getText();
            String pass = String.valueOf(txt_Password.getPassword());

            Employee employee = enterprise.getEmpDir().createEmp(txt_AdminName.getText());

            User_Acc account = enterprise.getUserAccDir().create_User_Account(uname, pass, employee, new Admin());
            populate_AdminTable(enterprise);

            populate_AdminTable(enterprise);

            JOptionPane.showMessageDialog(null, new JLabel("<html><h2>New Admin<font color='green'><I> credentials</I></font> created!</h2></html>"));

            dB4OUtil.storeSystem(system);

            txt_AdminName.setText("");
            txt_UserName.setText("");
            txt_Password.setText("");
            txt_Name.setText("");
            txt_AdminName.setEnabled(false);
            txt_UserName.setEnabled(false);
            txt_Password.setEnabled(false);
            txt_Name.setEnabled(false);
        }


    }//GEN-LAST:event_create_admin

    private void enterprise_JTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterprise_JTableMouseClicked
        int row = enterprise_JTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Please select<font color='red'> a row</font> from the<font color='green'> Table</I></font></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);

            return;
        }
        Enterprise enterprise2 = (Enterprise) enterprise_JTable.getValueAt(row, 0);
        enterprise = enterprise2;

        txt_Name.setText(enterprise2.getName());
        txt_AdminName.setEnabled(true);
        txt_UserName.setEnabled(true);
        txt_Password.setEnabled(true);

        populate_AdminTable(enterprise2);

    }//GEN-LAST:event_enterprise_JTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAdmin;
    private javax.swing.JTable enterprise_JTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbl_AdminUserName;
    private javax.swing.JTextField txt_AdminName;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
