/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Doctor;
import Plasma_DB4OUtil.DB4OUtil;
import Plasma.EcoSystem;
import Plasma_Enterprise.Enterprise;
import Plasma_Association.Doctor_Association;
import Plasma_User_Account.User_Acc;
import Plasma_Work_Queue.Work_Req;
import HomePages.TableFormat;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RST
 */
public class Manage_Doctor_Request_JPanel extends javax.swing.JPanel {

    //Creates new form PatientList
    private EcoSystem system;
    private User_Acc user_Acc;
    private Doctor_Association doctor;
    private Enterprise enterprise;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public Manage_Doctor_Request_JPanel(EcoSystem system, User_Acc userAccount, Doctor_Association doctorOrganization, Enterprise enterprise) {
        initComponents();
        this.system = system;
        this.user_Acc = userAccount;
        this.doctor = doctorOrganization;
        this.enterprise = enterprise;
        tblDoctorOrganisation.getTableHeader().setDefaultRenderer(new TableFormat());
        tblDoctor.getTableHeader().setDefaultRenderer(new TableFormat());
        view_patient_Table();
        view_Doctor_Patient_Table();

    }

    public void view_patient_Table() {
        DefaultTableModel m = (DefaultTableModel) tblDoctorOrganisation.getModel();
        m.setRowCount(0);
        for (Work_Req request : doctor.getWorkQueue().getWork_Req_List()) {
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getSummary();
            row[2] = request.getPatient();
            row[3] = request.getPatient().getName();
            row[4] = request.getStatus();
            m.addRow(row);
        }
    }

    public void view_Doctor_Patient_Table() {
        DefaultTableModel model = (DefaultTableModel) tblDoctor.getModel();
        model.setRowCount(0);
        for (Work_Req request : user_Acc.getWorkQueue().getWork_Req_List()) {
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getPatient();
            row[2] = request.getPatient().getName();
            row[3] = request.getUser_Acc().getUsername();
            row[4] = request.getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAssignToMe = new javax.swing.JButton();
        btnTreatmentDone = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDoctorOrganisation = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDoctor = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIST OF PATIENTS IN NEED OF PLASMA TREATMENT ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 690, -1));

        btnAssignToMe.setBackground(new java.awt.Color(31, 31, 31));
        btnAssignToMe.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        btnAssignToMe.setText("ASSIGN TO ME");
        btnAssignToMe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assign_button(evt);
            }
        });
        add(btnAssignToMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 170, 40));

        btnTreatmentDone.setBackground(new java.awt.Color(31, 31, 31));
        btnTreatmentDone.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        btnTreatmentDone.setText("COMPLETED TREATMENT");
        btnTreatmentDone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTreatmentDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completed_treatment(evt);
            }
        });
        add(btnTreatmentDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 740, 270, 40));

        tblDoctorOrganisation.setBackground(new java.awt.Color(102, 0, 102));
        tblDoctorOrganisation.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblDoctorOrganisation.setForeground(new java.awt.Color(255, 255, 255));
        tblDoctorOrganisation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REQUEST NUMBER", "SUMMARY", "PATIENT UID", "PATIENT NAME", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoctorOrganisation.setGridColor(new java.awt.Color(0, 0, 0));
        tblDoctorOrganisation.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblDoctorOrganisation.setRowHeight(30);
        tblDoctorOrganisation.setShowVerticalLines(false);
        jScrollPane4.setViewportView(tblDoctorOrganisation);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 1430, 200));

        tblDoctor.setBackground(new java.awt.Color(102, 0, 102));
        tblDoctor.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblDoctor.setForeground(new java.awt.Color(255, 255, 255));
        tblDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REQUEST NUMBER", "PATIENT UID", "PATIENT NAME", "ASSIGNED TO", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoctor.setGridColor(new java.awt.Color(0, 0, 0));
        tblDoctor.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblDoctor.setRowHeight(30);
        tblDoctor.setShowVerticalLines(false);
        jScrollPane5.setViewportView(tblDoctor);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 1430, 210));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("REQUEST MANAGEMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 1631, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 442, 1420, 10));
    }// </editor-fold>//GEN-END:initComponents
    
    //assign patient to doctor
    private void assign_button(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assign_button
        // TODO add your handling code here:
        int row = tblDoctorOrganisation.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, new JLabel("Please select a request number from the table!!!"), "Warning", JOptionPane.WARNING_MESSAGE);
           
        } else {
            Work_Req r = (Work_Req) tblDoctorOrganisation.getValueAt(row, 0);
            System.out.println(r.getStatus());
            if (r.getStatus().equals("Assigned in Doctor Pool") || r.getStatus().equals("Assigned in Doctor ")) {
                r.setStatus("Assign to Doctor " + user_Acc.getUsername());
                r.setUser_Acc(user_Acc);
                user_Acc.getWorkQueue().getWork_Req_List().add(r);
            } else {
                JOptionPane.showMessageDialog(null, new JLabel("Work Request already in progress!!!!"), "Warning", JOptionPane.WARNING_MESSAGE);

            }
            dB4OUtil.storeSystem(system);
            view_patient_Table();
            view_Doctor_Patient_Table();
        }

    }//GEN-LAST:event_assign_button

    //View treated patients
    
    private void completed_treatment(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completed_treatment
        // TODO add your handling code here:
        int selectedRow = tblDoctor.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, new JLabel("Please select reuqest number from the table"), "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            Work_Req request = (Work_Req) tblDoctor.getValueAt(selectedRow, 0);
            request.setStatus("Treatment Done");
            request.getPatient().setState("Treatment Done");
            dB4OUtil.storeSystem(system);
            view_patient_Table();
            view_Doctor_Patient_Table();
            // CELEBRATION
            JFrame f = new JFrame("Thank You");
            f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            f.setSize(screenSize.width / 2, screenSize.height / 2);
            f.setResizable(false);
            f.setUndecorated(false);
            f.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
            f.setLayout(new BorderLayout());
            JPanel panel = new JPanel(new FlowLayout(FlowLayout.CENTER));
            JLabel jLabel = new JLabel(" ");
            jLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
            jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thankyou.jpg"))); // NOI18N

            panel.add(jLabel);
            f.getContentPane().add(panel, BorderLayout.NORTH);
            f.getContentPane().add(new Thank_you(), BorderLayout.CENTER);
            f.setVisible(true);
        }

    }//GEN-LAST:event_completed_treatment


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnTreatmentDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblDoctor;
    private javax.swing.JTable tblDoctorOrganisation;
    // End of variables declaration//GEN-END:variables
}
