/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Admin;
import Plasma_DB4OUtil.DB4OUtil;
import Plasma.EcoSystem;
import Plasma_Employee.Employee;
import Plasma_Enterprise.Enterprise;
import Plasma_Association.Association;
import Plasma_Association.Association_Dir;
import HomePages.TableFormat;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RST
 */
public class Manage_Employee_JPanel extends javax.swing.JPanel {

    private Association_Dir organization_Dir;
    private JPanel user_Process;
    EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    //Creates new form Manage Organization      
    public Manage_Employee_JPanel(JPanel userProcessContainer, Association_Dir organizationDir, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.user_Process = userProcessContainer;
        this.organization_Dir = organizationDir;
        this.system = system;

        associationJTable.getTableHeader().setDefaultRenderer(new TableFormat());
        //populate the organization combo box
        
        populateAssociationComboBox();
        enterpriseNameTextField1.setText(enterprise.getName());
    }
    public void populateAssociationComboBox() {
        associationJComboBox.removeAllItems();
        for (Association organization : organization_Dir.getAssociationList()) {
            associationJComboBox.addItem(organization);
        }
    }
    public void populateOrganizationEmpComboBox() {
        associationEmpJComboBox.removeAllItems();

        for (Association organization : organization_Dir.getAssociationList()) {
            associationEmpJComboBox.addItem(organization.getFirstName());
        }
    }
    private void populateTable(Association organization) {
        DefaultTableModel model = (DefaultTableModel) associationJTable.getModel();

        model.setRowCount(0);

        for (Employee employee : organization.getEmpDir().getEmpList()) {
            Object[] row = new Object[3];
            row[0] = organization;
            row[1] = organization.getFirstName();
            row[2] = employee;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameSeparator = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        associationJComboBox = new javax.swing.JComboBox();
        associationEmpJComboBox = new javax.swing.JComboBox();
        addJButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nameSeparator1 = new javax.swing.JSeparator();
        nameSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        nameSeparator4 = new javax.swing.JSeparator();
        enterpriseNameTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        associationJTable = new javax.swing.JTable();

        enterpriseNameTextField.setBackground(new java.awt.Color(55, 96, 128));
        enterpriseNameTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enterpriseNameTextField.setBorder(null);
        enterpriseNameTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        enterpriseNameTextField.setOpaque(false);
        enterpriseNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enterpriseNameTextFieldFocusGained(evt);
            }
        });
        enterpriseNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseNameTextFieldActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button(evt);
            }
        });
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, 50));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(1550, 70));

        jLabel5.setBackground(new java.awt.Color(31, 31, 31));
        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EMPLOYEE MANAGEMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1656, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, -1));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 400));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CREATE EMPLOYEE");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 233, 36));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EMPLOYEE NAME");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 180, 26));

        nameSeparator.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(nameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 300, 10));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ORGANIZATION TYPE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 200, 26));

        nameJTextField.setBackground(new java.awt.Color(0, 0, 0));
        nameJTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        nameJTextField.setForeground(new java.awt.Color(255, 255, 255));
        nameJTextField.setBorder(null);
        jPanel2.add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 220, 30));

        associationJComboBox.setBackground(new java.awt.Color(0, 0, 0));
        associationJComboBox.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        associationJComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                associationJComboBoxItemStateChanged(evt);
            }
        });
        associationJComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                associationJComboBoxMouseClicked(evt);
            }
        });
        associationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationJComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(associationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 210, 30));

        associationEmpJComboBox.setBackground(new java.awt.Color(0, 0, 0));
        associationEmpJComboBox.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jPanel2.add(associationEmpJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 222, 210, 30));

        addJButton.setBackground(new java.awt.Color(31, 31, 31));
        addJButton.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        addJButton.setText("CREATE EMPLOYEE");
        addJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_employee(evt);
            }
        });
        jPanel2.add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 190, 40));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ORGANIZATION NAME ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 220, 26));

        nameSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(nameSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 358, 300, -1));

        nameSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(nameSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 300, 10));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 370, 450));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("ENTERPRISE:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        nameSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        add(nameSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 200, 10));

        enterpriseNameTextField1.setBackground(new java.awt.Color(0, 0, 0));
        enterpriseNameTextField1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        enterpriseNameTextField1.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseNameTextField1.setBorder(null);
        add(enterpriseNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 190, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/workers.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 80, 130, 120));

        associationJTable.setBackground(new java.awt.Color(0, 0, 0));
        associationJTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 204)));
        associationJTable.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        associationJTable.setForeground(new java.awt.Color(255, 255, 255));
        associationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Type", "Organization Name", "Employee Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        associationJTable.setGridColor(new java.awt.Color(0, 0, 0));
        associationJTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        associationJTable.setRowHeight(30);
        associationJTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(associationJTable);
        if (associationJTable.getColumnModel().getColumnCount() > 0) {
            associationJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 750, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void create_employee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_employee
        String check1 = "";
        Association association = (Association) associationJComboBox.getSelectedItem();

        //check for valid inputs
        if (associationJComboBox.getSelectedItem() == null) {
            associationJComboBox.setBorder(BorderFactory.createLineBorder(Color.RED));
            associationJComboBox.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Select an<font color='red'> Organization Type</font> please!</I></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
            check1 = "don't go ahead";
        } else if (associationEmpJComboBox.getSelectedItem() == null) {
            associationEmpJComboBox.setBorder(BorderFactory.createLineBorder(Color.RED));
            associationEmpJComboBox.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Select an<font color='red'> Organization Name</font> please!</I></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
           check1 = "don't go ahead";
        } else if (nameJTextField.getText().isEmpty()) {
            nameJTextField.setBorder(BorderFactory.createLineBorder(Color.RED));
            nameJTextField.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Employee Name<font color='red'> can not</font> be same!</I></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
            check1 = "don't go ahead";
            return;
        } else {

            for (Employee employee : association.getEmpDir().getEmpList()) {

                if (employee.getName().equals(nameJTextField.getText())) {
                    JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Multiple employees <font color='red'> can not</font> have same name!</I></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
                    check1 = "don't go ahead";
                    return;
                }
            }
        }

        if (check1 == "") {

            //create employee
            
            String name = nameJTextField.getText();
            association.getEmpDir().createEmp(name);
            populateTable(association);

            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>New Employee</I><font color='green'> created </font><I>successfully!/I<></h2></html>"));
            nameJTextField.setText("");
            dB4OUtil.storeSystem(system);
        }
    }//GEN-LAST:event_create_employee

    private void associationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationJComboBoxActionPerformed
        Association a = (Association) associationJComboBox.getSelectedItem();
        if (a != null) {
            populateTable(a);
        }
    }//GEN-LAST:event_associationJComboBoxActionPerformed

    private void back_button(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button
        // TODO add your handling code here:
        user_Process.remove(this);
        CardLayout layout = (CardLayout) user_Process.getLayout();
        layout.previous(user_Process);
    }//GEN-LAST:event_back_button

    private void enterpriseNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterpriseNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseNameTextFieldFocusGained

    private void enterpriseNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseNameTextFieldActionPerformed

    private void associationJComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_associationJComboBoxMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_associationJComboBoxMouseClicked

    private void associationJComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_associationJComboBoxItemStateChanged
        // TODO add your handling code here:
        Association a = (Association) associationJComboBox.getSelectedItem();
        associationEmpJComboBox.removeAllItems();
        associationEmpJComboBox.addItem(a.getFirstName());

    }//GEN-LAST:event_associationJComboBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JComboBox associationEmpJComboBox;
    private javax.swing.JComboBox associationJComboBox;
    private javax.swing.JTable associationJTable;
    private javax.swing.JTextField enterpriseNameTextField;
    private javax.swing.JTextField enterpriseNameTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JSeparator nameSeparator1;
    private javax.swing.JSeparator nameSeparator3;
    private javax.swing.JSeparator nameSeparator4;
    // End of variables declaration//GEN-END:variables
}
