/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Legal_Officer;
import Plasma_DB4OUtil.DB4OUtil;
import Plasma.EcoSystem;
import Plasma_Enterprise.Enterprise;
import Plasma_Association.Legal_Officer_Association;
import Plasma_User_Account.User_Acc;
import Plasma_Work_Queue.Work_Req;
import HomePages.TableFormat;
import javax.swing.table.DefaultTableModel;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author RST
 */
public class Manage_Legal_Officer_Request_JPanel extends javax.swing.JPanel {
    
     //Creates new form Manage_Legal_Officer_Request
    
    private EcoSystem system;
    private User_Acc user_Acc;
    private Legal_Officer_Association legal_officer;
    private Enterprise e;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public Manage_Legal_Officer_Request_JPanel(EcoSystem system, User_Acc userAccount, Legal_Officer_Association legalofficerorganization, Enterprise enterprise) {
        initComponents();
        this.system = system;
        this.user_Acc = userAccount;
        this.legal_officer = legalofficerorganization;
        this.e = enterprise;

        tblLegalOrganisation.getTableHeader().setDefaultRenderer(new TableFormat());
        tblLegalOfficer.getTableHeader().setDefaultRenderer(new TableFormat());
        view_patient_association_Table();
        view_Legal_Patient_Table();
    }
    public void view_patient_association_Table() {
        DefaultTableModel table = (DefaultTableModel) tblLegalOrganisation.getModel();

        table.setRowCount(0);

        for (Work_Req work : legal_officer.getWorkQueue().getWork_Req_List()) {
            Object[] row = new Object[6];
            row[0] = work;
            row[1] = work.getSummary();
            row[2] = work.getPatient();
            row[3] = work.getPatient().getName();
            row[4] = work.getPatient().getEmailID();
            row[5] = work.getStatus();

            table.addRow(row);
        }
    }

    public void view_Legal_Patient_Table() {
        DefaultTableModel table=  (DefaultTableModel) tblLegalOfficer.getModel();

        table.setRowCount(0);

        for (Work_Req work : user_Acc.getWorkQueue().getWork_Req_List()) {
            Object[] row = new Object[6];
            row[0] = work;
            row[1] = work.getPatient();
            row[2] = work.getPatient().getName();
            row[3] = work.getPatient().getEmailID();
            row[4] = work.getUser_Acc().getUsername();
            row[5] = work.getStatus();

            table.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssign = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLegalOrganisation = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLegalOfficer = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        toTextField = new javax.swing.JTextField();
        fromTextField = new javax.swing.JTextField();
        subjectTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextField = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAssign.setBackground(new java.awt.Color(31, 31, 31));
        btnAssign.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnAssign.setText("ASSIGN TO ME ");
        btnAssign.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assign_me(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 240, 40));

        tblLegalOrganisation.setBackground(new java.awt.Color(0, 0, 0));
        tblLegalOrganisation.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblLegalOrganisation.setForeground(new java.awt.Color(255, 255, 255));
        tblLegalOrganisation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Summary", "Patient UID", "Patient Name", "Email", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLegalOrganisation.setGridColor(new java.awt.Color(0, 0, 0));
        tblLegalOrganisation.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblLegalOrganisation.setRowHeight(30);
        tblLegalOrganisation.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tblLegalOrganisation);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 1280, 190));

        tblLegalOfficer.setBackground(new java.awt.Color(0, 0, 0));
        tblLegalOfficer.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblLegalOfficer.setForeground(new java.awt.Color(255, 255, 255));
        tblLegalOfficer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Patient UID", "Patient Name", "Email", "Assigned to", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLegalOfficer.setGridColor(new java.awt.Color(0, 0, 0));
        tblLegalOfficer.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblLegalOfficer.setRowHeight(30);
        tblLegalOfficer.setShowVerticalLines(false);
        jScrollPane4.setViewportView(tblLegalOfficer);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 1280, 190));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("CONSENT REQUEST FOR PATIENT TREATMENT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 1556, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("TO:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("FROM::");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("SUBJECT:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("MESSAGE: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 700, -1, -1));

        jButton1.setBackground(new java.awt.Color(31, 31, 31));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("SEND CONSENT FORM ON MAIL");
        jButton1.setActionCommand("SEND CONSENT FORM IN EMAIL");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_consent_on_email(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 660, 290, 40));

        toTextField.setBackground(new java.awt.Color(0, 0, 0));
        toTextField.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        toTextField.setForeground(new java.awt.Color(255, 255, 255));
        toTextField.setText("aedbdrst@gmail.com");
        toTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTextFieldActionPerformed(evt);
            }
        });
        add(toTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 320, -1));

        fromTextField.setBackground(new java.awt.Color(0, 0, 0));
        fromTextField.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        fromTextField.setForeground(new java.awt.Color(255, 255, 255));
        fromTextField.setText("aedbdrst@gmail.com");
        fromTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromTextFieldActionPerformed(evt);
            }
        });
        add(fromTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 320, -1));

        subjectTextField.setBackground(new java.awt.Color(0, 0, 0));
        subjectTextField.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        subjectTextField.setForeground(new java.awt.Color(255, 255, 255));
        subjectTextField.setText("Legal Consent");
        add(subjectTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 320, -1));

        messageTextField.setBackground(new java.awt.Color(0, 0, 0));
        messageTextField.setColumns(20);
        messageTextField.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        messageTextField.setForeground(new java.awt.Color(255, 255, 255));
        messageTextField.setRows(5);
        messageTextField.setText("Hi,\n\nThanks for your interest .\nRequest you to please sign the Consent form for Plasma  Treatment.\n\nThank you");
        jScrollPane1.setViewportView(messageTextField);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 710, 690, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void assign_me(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assign_me
        int selected = tblLegalOrganisation.getSelectedRow();

        if (selected < 0) {
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Please select<font color='red'> a row</font> from the<font color='green'> table</I></font></h2></html>"), "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            Work_Req work = (Work_Req) tblLegalOrganisation.getValueAt(selected, 0);

            if (work.getStatus().equals("Assigned to Legal Pool")) {
                work.setStatus("Assign to Legal Officer" + user_Acc.getUsername());
                work.setUser_Acc(user_Acc);
                user_Acc.getWorkQueue().getWork_Req_List().add(work);
            } else {
                JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Work Request is<font color='red'> already</font> in progress!</I></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
            }
            dB4OUtil.storeSystem(system);
            view_patient_association_Table();
            view_Legal_Patient_Table();
        }
    }//GEN-LAST:event_assign_me

    private void send_consent_on_email(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_consent_on_email
         if (toTextField.getText().equals("") || subjectTextField.getText().equals("") || messageTextField.getText().equals("")) {

            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>All fields are</I><font color='red'> mandatory</font>!</h2></html>"), "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            String toMail = toTextField.getText();
            //       String toEmail = "yashwant7kotipalli@gmail.com";
            //       final String fromEmail = "yashwant7kotipalli@gmail.com";
            final String fromEmail = fromTextField.getText();
            final String fromEmailPswd = "teamtitans"; //your email password
            String sub = subjectTextField.getText();

            Properties prop = new Properties();
            prop.put("mail.smtp.starttls.enable", "true");
            prop.put("mail.smtp.EnableSSL.enable", "true");
            prop.put("mail.smtp.host", "smtp.gmail.com");
            prop.put("mail.smtp.auth", "true");
            prop.put("mail.debug", "true");
            prop.put("mail.smtp.host", "smtp.gmail.com");
            prop.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            prop.setProperty("mail.smtp.socketFactory.fallback", "false");
            prop.setProperty("mail.smtp.port", "465");
            prop.setProperty("mail.smtp.socketFactory.port", "465");

            Session session = Session.getDefaultInstance(prop, new javax.mail.Authenticator() {

                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(fromEmail, fromEmailPswd);
                }
            });

            try {
                MimeMessage msg = new MimeMessage(session);
                msg.setFrom(new InternetAddress(fromEmail));
                msg.addRecipient(Message.RecipientType.TO, new InternetAddress(toMail));
                msg.setSubject(sub);
                msg.setText(messageTextField.getText());
                Transport.send(msg);
            } catch (MessagingException ex) {
                System.out.println("" + ex);
            }

            int selectedRow = tblLegalOfficer.getSelectedRow();

            if (selectedRow < 0) {
                JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Please select<font color='red'> a row</font> from the<font color='green'> table</I></font></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);

            } else {
                Work_Req request = (Work_Req) tblLegalOfficer.getValueAt(selectedRow, 0);

                request.setStatus("Consent form sent");

                dB4OUtil.storeSystem(system);

                view_patient_association_Table();
                view_Legal_Patient_Table();

                JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Consent Form<font color='green'> sent</font> successfully!</I></font></h2></html>"), "Info", JOptionPane.INFORMATION_MESSAGE);

                }
        }
    }//GEN-LAST:event_send_consent_on_email

    private void toTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toTextFieldActionPerformed

    private void fromTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea messageTextField;
    private javax.swing.JTextField subjectTextField;
    private javax.swing.JTable tblLegalOfficer;
    private javax.swing.JTable tblLegalOrganisation;
    private javax.swing.JTextField toTextField;
    // End of variables declaration//GEN-END:variables
}
