/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Legal_Officer;
import Plasma_DB4OUtil.DB4OUtil;
import Plasma.EcoSystem;
import Plasma_Enterprise.Enterprise;
import Plasma_Network_Cities.Network_Cities;
import Plasma_Association.Association;
import Plasma_Association.Plasma_Bank_Association;
import Plasma_User_Account.User_Acc;
import Plasma_Work_Queue.Work_Req;
import HomePages.TableFormat;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Properties;
import javax.imageio.ImageIO;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RST
 */
public class Patient_Consent_JPanel extends javax.swing.JPanel {

    //Creates new form Patient_Consent
    
    private EcoSystem system;
    private User_Acc user;
    private Network_Cities net;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public Patient_Consent_JPanel(EcoSystem system, User_Acc userAccount, Network_Cities network) {
        initComponents();
        this.system = system;
        this.user = userAccount;
        this.net = network;
        tblPatientConsent.getTableHeader().setDefaultRenderer(new TableFormat());
        view_Patient_Consent_Table();
    }

    public void view_Patient_Consent_Table() {
        DefaultTableModel table = (DefaultTableModel) tblPatientConsent.getModel();

        table.setRowCount(0);

        for (Work_Req work : user.getWorkQueue().getWork_Req_List()) {
            Object[] row = new Object[5];
            row[0] = work;
            row[1] = work.getPatient();
            row[2] = work.getPatient().getName();
            row[3] = work.getPatient().getEmailID();
            row[4] = work.getStatus();

            table.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientConsent = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnSi8gn = new javax.swing.JButton();
        btnApproval = new javax.swing.JButton();
        btnDisapproval = new javax.swing.JButton();
        btnConsentForm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        toTextField = new javax.swing.JTextField();
        fromTextField = new javax.swing.JTextField();
        subjectTextField = new javax.swing.JTextField();
        messageTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lblConsent = new javax.swing.JLabel();
        btnPatientAgreement = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPatientConsent.setBackground(new java.awt.Color(0, 0, 0));
        tblPatientConsent.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblPatientConsent.setForeground(new java.awt.Color(255, 255, 255));
        tblPatientConsent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Patient ID", "Patient Name", "Patient email", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatientConsent.setFocusable(false);
        tblPatientConsent.setGridColor(new java.awt.Color(0, 0, 0));
        tblPatientConsent.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblPatientConsent.setRowHeight(30);
        tblPatientConsent.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblPatientConsent);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 1330, 220));

        jButton1.setBackground(new java.awt.Color(31, 31, 31));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("SEND CONSENT FORM ON MAIL");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_consent(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, 360, 40));

        btnSi8gn.setBackground(new java.awt.Color(31, 31, 31));
        btnSi8gn.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnSi8gn.setText("SIGN THE FORM");
        btnSi8gn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSi8gn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_form(evt);
            }
        });
        add(btnSi8gn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 690, 200, 40));

        btnApproval.setBackground(new java.awt.Color(31, 31, 31));
        btnApproval.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnApproval.setText("GIVE LEGAL APPROVAL");
        btnApproval.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legal_approval(evt);
            }
        });
        add(btnApproval, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 690, 260, 40));

        btnDisapproval.setBackground(new java.awt.Color(31, 31, 31));
        btnDisapproval.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnDisapproval.setText("DISAPPROVE");
        btnDisapproval.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDisapproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disapprove_button(evt);
            }
        });
        add(btnDisapproval, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 690, 140, 40));

        btnConsentForm.setBackground(new java.awt.Color(31, 31, 31));
        btnConsentForm.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnConsentForm.setText("DISPLAY FORM FOR CONSENT");
        btnConsentForm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsentForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_consent_form(evt);
            }
        });
        add(btnConsentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, 250, 40));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("TO:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("FROM::");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("SUBJECT:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("MESSAGE:: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, -1, -1));

        toTextField.setBackground(new java.awt.Color(0, 0, 0));
        toTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        toTextField.setForeground(new java.awt.Color(255, 255, 255));
        add(toTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 290, 40));

        fromTextField.setBackground(new java.awt.Color(0, 0, 0));
        fromTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        fromTextField.setForeground(new java.awt.Color(255, 255, 255));
        fromTextField.setText("aedbdrst@gmail.com");
        fromTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromTextFieldActionPerformed(evt);
            }
        });
        add(fromTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 290, 40));

        subjectTextField.setBackground(new java.awt.Color(0, 0, 0));
        subjectTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        subjectTextField.setForeground(new java.awt.Color(255, 255, 255));
        add(subjectTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 290, 40));

        messageTextField.setBackground(new java.awt.Color(0, 0, 0));
        messageTextField.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        messageTextField.setForeground(new java.awt.Color(255, 255, 255));
        messageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextFieldActionPerformed(evt);
            }
        });
        add(messageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 290, 130));

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("STATUS FOR TREATMENT CONSENT  LETTER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 1566, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, -1));

        lblConsent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204)));
        add(lblConsent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 420, 230, 250));

        btnPatientAgreement.setBackground(new java.awt.Color(31, 31, 31));
        btnPatientAgreement.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnPatientAgreement.setText("AGREEMENT FOR PATIENT");
        btnPatientAgreement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPatientAgreement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreement_patient(evt);
            }
        });
        add(btnPatientAgreement, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 359, 230, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void legal_approval(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legal_approval
        int selectedRow = tblPatientConsent.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Please select<font color='red'> a row</font> from the<font color='green'> table</I></font></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            Work_Req work = (Work_Req) tblPatientConsent.getValueAt(selectedRow, 0);

            work.setStatus("Legally Approved. Forwarding to Plasma Bank");
            dB4OUtil.storeSystem(system);
            view_Patient_Consent_Table();
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Legally<font color='green'> approved</font> successfully!</I></font></h2></html>"), "Info", JOptionPane.INFORMATION_MESSAGE);
            Enterprise ent = null;
            Association org = null;

            for (Enterprise enter : net.getEnterprise_Dir().getEnt_List()) {
                if (enter.getEnterprise_type().toString().equals("PlasmaBank")) {

                    ent = enter;
                    System.out.println(enter);
                    break;
                }
            }

            for (Association association : ent.getAssociationDirectory().getAssociationList()) {
                if (association instanceof Plasma_Bank_Association) {
                    org = association;
                    break;
                }
            }

            if (org != null) {
                org.getWorkQueue().getWork_Req_List().add(work);
                System.out.println(org.getName() + "Orgcheck");
            } else {
                JOptionPane.showMessageDialog(null, "No organization present", "Error", JOptionPane.ERROR_MESSAGE);
            }

            User_Acc u = null;
            for (User_Acc userAcc : org.getUserAccDir().getUser_Account_List()) {
                u = userAcc;
                u.getWorkQueue().getWork_Req_List().add(work);
                break;
            }
        }
    }//GEN-LAST:event_legal_approval

    private void send_consent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_consent
   String toEmail = toTextField.getText();
        final String fromEmail = fromTextField.getText();
        final String fromEmailPassword = "teamtitans"; //your email password
        String subject = subjectTextField.getText();
        Properties p = new Properties();
        p.put("mail.smtp.starttls.enable", "true");
        p.put("mail.smtp.EnableSSL.enable", "true");
        p.put("mail.smtp.host", "smtp.gmail.com");
        p.put("mail.smtp.auth", "true");
        p.put("mail.debug", "true");
        p.put("mail.smtp.host", "smtp.gmail.com");
        p.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        p.setProperty("mail.smtp.socketFactory.fallback", "false");
        p.setProperty("mail.smtp.port", "465");
        p.setProperty("mail.smtp.socketFactory.port", "465");

        Session s;
        s = Session.getDefaultInstance(p, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(fromEmail, fromEmailPassword);
            }
        });

        try {
            MimeMessage msg = new MimeMessage(s);
            msg.setFrom(new InternetAddress(fromEmail));
            msg.addRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));
            msg.setSubject(subject);
            msg.setText(messageTextField.getText());
            Transport.send(msg);
        } catch (Exception ex) {
            System.out.println("" + ex);
        }

        System.out.println("Sent mail successfully ...");
    }//GEN-LAST:event_send_consent

    private void display_consent_form(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_consent_form
            BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("organ_Agreement.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img1.getScaledInstance(lblConsent.getWidth(), lblConsent.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lblConsent.setIcon(imageIcon);


    }//GEN-LAST:event_display_consent_form

    private void sign_form(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_form
        // TODO add your handling code here:
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("organ_Agreement_DonorReceiverAdvocate.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimension = img.getScaledInstance(lblConsent.getWidth(), lblConsent.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimension);
        lblConsent.setIcon(imageIcon);


    }//GEN-LAST:event_sign_form

    private void agreement_patient(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreement_patient
        // TODO add your handling code here:
        BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("organ_Agreement_Donor.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimension = img1.getScaledInstance(lblConsent.getWidth(), lblConsent.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimension);
        lblConsent.setIcon(imageIcon);

    }//GEN-LAST:event_agreement_patient

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextFieldActionPerformed

    private void disapprove_button(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disapprove_button
        // TODO add your handling code here:

        int row = tblPatientConsent.getSelectedRow();

        if (row < 0) {
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I>Please select<font color='red'> a row</font> from the<font color='green'> table</I></font></h2></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Work_Req req = (Work_Req) tblPatientConsent.getValueAt(row, 0);

            req.setStatus("Disapproved");
            req.setUser_Acc(user);
            user.getWorkQueue().getWork_Req_List().add(req);

            dB4OUtil.storeSystem(system);
            view_Patient_Consent_Table();
            JOptionPane.showMessageDialog(null, new JLabel("<html><h2><I><font color='red'> Legally Disapproved!</I></font></h2></html>"), "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_disapprove_button

    private void fromTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromTextFieldActionPerformed
      
    }//GEN-LAST:event_fromTextFieldActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproval;
    private javax.swing.JButton btnConsentForm;
    private javax.swing.JButton btnDisapproval;
    private javax.swing.JButton btnPatientAgreement;
    private javax.swing.JButton btnSi8gn;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsent;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JTextField subjectTextField;
    private javax.swing.JTable tblPatientConsent;
    private javax.swing.JTextField toTextField;
    // End of variables declaration//GEN-END:variables

}
